/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using OPayments.SDK.Api;
using OPayments.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace OPayments.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing RefundsApi
    /// </summary>
    public sealed class RefundsApiTests : ApiTestsBase
    {
        private readonly IRefundsApi _instance;

        public RefundsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IRefundsApi>();
        }

        /// <summary>
        /// Test CreatePaymentRefund
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreatePaymentRefundAsyncTest()
        {
            Guid paymentId = default!;
            CreateRefundRequest createRefundRequest = default!;
            var response = await _instance.CreatePaymentRefundAsync(paymentId, createRefundRequest);
            var model = response.Ok();
            Assert.IsType<OPayments.SDK.Model.Refund>(model);
        }

        /// <summary>
        /// Test GetPaymentRefund
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetPaymentRefundAsyncTest()
        {
            Guid paymentId = default!;
            var response = await _instance.GetPaymentRefundAsync(paymentId);
            var model = response.Ok();
            Assert.IsType<OPayments.SDK.Model.Refund>(model);
        }
    }
}
