// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// Balance
    /// </summary>
    public partial class Balance : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Balance" /> class.
        /// </summary>
        /// <param name="projectId">projectId</param>
        /// <param name="varBalance">varBalance</param>
        /// <param name="currency">currency</param>
        [JsonConstructor]
        public Balance(Guid projectId, int varBalance, CurrencyEnum currency)
        {
            ProjectId = projectId;
            VarBalance = varBalance;
            Currency = currency;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Currency
        /// </summary>
        public enum CurrencyEnum
        {
            /// <summary>
            /// Enum RUB for value: RUB
            /// </summary>
            RUB = 1
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CurrencyEnum CurrencyEnumFromString(string value)
        {
            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            throw new NotImplementedException($"Could not convert value to type CurrencyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CurrencyEnum? CurrencyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CurrencyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CurrencyEnumToJsonValue(CurrencyEnum value)
        {
            if (value == CurrencyEnum.RUB)
                return "RUB";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public CurrencyEnum Currency { get; set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("projectId")]
        public Guid ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets VarBalance
        /// </summary>
        [JsonPropertyName("balance")]
        public int VarBalance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Balance {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  VarBalance: ").Append(VarBalance).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Balance" />
    /// </summary>
    public partial class BalanceJsonConverter : JsonConverter<Balance>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="BalanceJsonConverter" /> class.
        /// </summary>
        public BalanceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Balance" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Balance Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> projectId = default;
            Option<int?> varBalance = default;
            Option<Balance.CurrencyEnum?> currency = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "projectId":
                            projectId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "balance":
                            varBalance = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "currency":
                            string? currencyRawValue = utf8JsonReader.GetString();
                            if (currencyRawValue != null)
                            {
                                Balance.CurrencyEnum? currencyValue = Balance.CurrencyEnumFromStringOrDefault(currencyRawValue);
                                if (currencyValue == null)
                                    throw new JsonException();
                                currency = new Option<Balance.CurrencyEnum?>(currencyValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!projectId.IsSet)
                throw new ArgumentException("Property is required for class Balance.", nameof(projectId));

            if (!varBalance.IsSet)
                throw new ArgumentException("Property is required for class Balance.", nameof(varBalance));

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class Balance.", nameof(currency));

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class Balance.");

            if (varBalance.IsSet && varBalance.Value == null)
                throw new ArgumentNullException(nameof(varBalance), "Property is not nullable for class Balance.");

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class Balance.");

            return new Balance(projectId.Value!.Value!, varBalance.Value!.Value!, currency.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Balance" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="balance"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Balance balance, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, balance, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Balance" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="balance"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Balance balance, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("projectId", balance.ProjectId);

            writer.WriteNumber("balance", balance.VarBalance);

            var currencyRawValue = Balance.CurrencyEnumToJsonValue(balance.Currency);
            writer.WriteString("currency", currencyRawValue);
        }
    }
}
