// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// CreateTpayPaymentRequest
    /// </summary>
    public partial class CreateTpayPaymentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTpayPaymentRequest" /> class.
        /// </summary>
        /// <param name="orderId">Идентификатор заказа в системе мерчанта.</param>
        /// <param name="amount">Сумма в копейках.</param>
        /// <param name="metadata">metadata</param>
        /// <param name="callbackUrl">HTTPS-адрес для уведомлений о платеже.</param>
        /// <param name="successUrl">HTTPS-адрес для успешной оплаты.</param>
        /// <param name="failedUrl">HTTPS-адрес для отменённой оплаты.</param>
        /// <param name="description">description</param>
        [JsonConstructor]
        public CreateTpayPaymentRequest(string orderId, int amount, TpayPaymentMetadata metadata, string callbackUrl, string successUrl, string failedUrl, Option<string?> description = default)
        {
            OrderId = orderId;
            Amount = amount;
            Metadata = metadata;
            CallbackUrl = callbackUrl;
            SuccessUrl = successUrl;
            FailedUrl = failedUrl;
            DescriptionOption = description;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Идентификатор заказа в системе мерчанта.
        /// </summary>
        /// <value>Идентификатор заказа в системе мерчанта.</value>
        [JsonPropertyName("orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// Сумма в копейках.
        /// </summary>
        /// <value>Сумма в копейках.</value>
        [JsonPropertyName("amount")]
        public int Amount { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [JsonPropertyName("metadata")]
        public TpayPaymentMetadata Metadata { get; set; }

        /// <summary>
        /// HTTPS-адрес для уведомлений о платеже.
        /// </summary>
        /// <value>HTTPS-адрес для уведомлений о платеже.</value>
        [JsonPropertyName("callbackUrl")]
        public string CallbackUrl { get; set; }

        /// <summary>
        /// HTTPS-адрес для успешной оплаты.
        /// </summary>
        /// <value>HTTPS-адрес для успешной оплаты.</value>
        [JsonPropertyName("successUrl")]
        public string SuccessUrl { get; set; }

        /// <summary>
        /// HTTPS-адрес для отменённой оплаты.
        /// </summary>
        /// <value>HTTPS-адрес для отменённой оплаты.</value>
        [JsonPropertyName("failedUrl")]
        public string FailedUrl { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTpayPaymentRequest {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  CallbackUrl: ").Append(CallbackUrl).Append("\n");
            sb.Append("  SuccessUrl: ").Append(SuccessUrl).Append("\n");
            sb.Append("  FailedUrl: ").Append(FailedUrl).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // OrderId (string) maxLength
            if (this.OrderId != null && this.OrderId.Length > 128)
            {
                yield return new ValidationResult("Invalid value for OrderId, length must be less than 128.", new [] { "OrderId" });
            }

            // OrderId (string) minLength
            if (this.OrderId != null && this.OrderId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for OrderId, length must be greater than 1.", new [] { "OrderId" });
            }

            // Amount (int) minimum
            if (this.Amount < (int)1)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 1.", new [] { "Amount" });
            }

            // CallbackUrl (string) maxLength
            if (this.CallbackUrl != null && this.CallbackUrl.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for CallbackUrl, length must be less than 2048.", new [] { "CallbackUrl" });
            }

            if (this.CallbackUrl != null) {
                // CallbackUrl (string) pattern
                Regex regexCallbackUrl = new Regex(@"^https://", RegexOptions.CultureInvariant);

                if (!regexCallbackUrl.Match(this.CallbackUrl).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CallbackUrl, must match a pattern of " + regexCallbackUrl, new [] { "CallbackUrl" });
                }
            }

            // SuccessUrl (string) maxLength
            if (this.SuccessUrl != null && this.SuccessUrl.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for SuccessUrl, length must be less than 2048.", new [] { "SuccessUrl" });
            }

            if (this.SuccessUrl != null) {
                // SuccessUrl (string) pattern
                Regex regexSuccessUrl = new Regex(@"^https://", RegexOptions.CultureInvariant);

                if (!regexSuccessUrl.Match(this.SuccessUrl).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SuccessUrl, must match a pattern of " + regexSuccessUrl, new [] { "SuccessUrl" });
                }
            }

            // FailedUrl (string) maxLength
            if (this.FailedUrl != null && this.FailedUrl.Length > 2048)
            {
                yield return new ValidationResult("Invalid value for FailedUrl, length must be less than 2048.", new [] { "FailedUrl" });
            }

            if (this.FailedUrl != null) {
                // FailedUrl (string) pattern
                Regex regexFailedUrl = new Regex(@"^https://", RegexOptions.CultureInvariant);

                if (!regexFailedUrl.Match(this.FailedUrl).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FailedUrl, must match a pattern of " + regexFailedUrl, new [] { "FailedUrl" });
                }
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 255.", new [] { "Description" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateTpayPaymentRequest" />
    /// </summary>
    public partial class CreateTpayPaymentRequestJsonConverter : JsonConverter<CreateTpayPaymentRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTpayPaymentRequestJsonConverter" /> class.
        /// </summary>
        public CreateTpayPaymentRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateTpayPaymentRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateTpayPaymentRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> orderId = default;
            Option<int?> amount = default;
            Option<TpayPaymentMetadata?> metadata = default;
            Option<string?> callbackUrl = default;
            Option<string?> successUrl = default;
            Option<string?> failedUrl = default;
            Option<string?> description = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "orderId":
                            orderId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "metadata":
                            metadata = new Option<TpayPaymentMetadata?>(JsonSerializer.Deserialize<TpayPaymentMetadata>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "callbackUrl":
                            callbackUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "successUrl":
                            successUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "failedUrl":
                            failedUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!orderId.IsSet)
                throw new ArgumentException("Property is required for class CreateTpayPaymentRequest.", nameof(orderId));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class CreateTpayPaymentRequest.", nameof(amount));

            if (!metadata.IsSet)
                throw new ArgumentException("Property is required for class CreateTpayPaymentRequest.", nameof(metadata));

            if (!callbackUrl.IsSet)
                throw new ArgumentException("Property is required for class CreateTpayPaymentRequest.", nameof(callbackUrl));

            if (!successUrl.IsSet)
                throw new ArgumentException("Property is required for class CreateTpayPaymentRequest.", nameof(successUrl));

            if (!failedUrl.IsSet)
                throw new ArgumentException("Property is required for class CreateTpayPaymentRequest.", nameof(failedUrl));

            if (orderId.IsSet && orderId.Value == null)
                throw new ArgumentNullException(nameof(orderId), "Property is not nullable for class CreateTpayPaymentRequest.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class CreateTpayPaymentRequest.");

            if (metadata.IsSet && metadata.Value == null)
                throw new ArgumentNullException(nameof(metadata), "Property is not nullable for class CreateTpayPaymentRequest.");

            if (callbackUrl.IsSet && callbackUrl.Value == null)
                throw new ArgumentNullException(nameof(callbackUrl), "Property is not nullable for class CreateTpayPaymentRequest.");

            if (successUrl.IsSet && successUrl.Value == null)
                throw new ArgumentNullException(nameof(successUrl), "Property is not nullable for class CreateTpayPaymentRequest.");

            if (failedUrl.IsSet && failedUrl.Value == null)
                throw new ArgumentNullException(nameof(failedUrl), "Property is not nullable for class CreateTpayPaymentRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class CreateTpayPaymentRequest.");

            return new CreateTpayPaymentRequest(orderId.Value!, amount.Value!.Value!, metadata.Value!, callbackUrl.Value!, successUrl.Value!, failedUrl.Value!, description);
        }

        /// <summary>
        /// Serializes a <see cref="CreateTpayPaymentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createTpayPaymentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateTpayPaymentRequest createTpayPaymentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createTpayPaymentRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateTpayPaymentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createTpayPaymentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateTpayPaymentRequest createTpayPaymentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createTpayPaymentRequest.OrderId == null)
                throw new ArgumentNullException(nameof(createTpayPaymentRequest.OrderId), "Property is required for class CreateTpayPaymentRequest.");

            if (createTpayPaymentRequest.Metadata == null)
                throw new ArgumentNullException(nameof(createTpayPaymentRequest.Metadata), "Property is required for class CreateTpayPaymentRequest.");

            if (createTpayPaymentRequest.CallbackUrl == null)
                throw new ArgumentNullException(nameof(createTpayPaymentRequest.CallbackUrl), "Property is required for class CreateTpayPaymentRequest.");

            if (createTpayPaymentRequest.SuccessUrl == null)
                throw new ArgumentNullException(nameof(createTpayPaymentRequest.SuccessUrl), "Property is required for class CreateTpayPaymentRequest.");

            if (createTpayPaymentRequest.FailedUrl == null)
                throw new ArgumentNullException(nameof(createTpayPaymentRequest.FailedUrl), "Property is required for class CreateTpayPaymentRequest.");

            if (createTpayPaymentRequest.DescriptionOption.IsSet && createTpayPaymentRequest.Description == null)
                throw new ArgumentNullException(nameof(createTpayPaymentRequest.Description), "Property is required for class CreateTpayPaymentRequest.");

            writer.WriteString("orderId", createTpayPaymentRequest.OrderId);

            writer.WriteNumber("amount", createTpayPaymentRequest.Amount);

            writer.WritePropertyName("metadata");
            JsonSerializer.Serialize(writer, createTpayPaymentRequest.Metadata, jsonSerializerOptions);
            writer.WriteString("callbackUrl", createTpayPaymentRequest.CallbackUrl);

            writer.WriteString("successUrl", createTpayPaymentRequest.SuccessUrl);

            writer.WriteString("failedUrl", createTpayPaymentRequest.FailedUrl);

            if (createTpayPaymentRequest.DescriptionOption.IsSet)
                writer.WriteString("description", createTpayPaymentRequest.Description);
        }
    }
}
