// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// ErrorErrorDetailsInner
    /// </summary>
    public partial class ErrorErrorDetailsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorErrorDetailsInner" /> class.
        /// </summary>
        /// <param name="field">field</param>
        /// <param name="code">code</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public ErrorErrorDetailsInner(string field, string code, string message)
        {
            Field = field;
            Code = code;
            Message = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        [JsonPropertyName("field")]
        public string Field { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ErrorErrorDetailsInner {\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ErrorErrorDetailsInner" />
    /// </summary>
    public partial class ErrorErrorDetailsInnerJsonConverter : JsonConverter<ErrorErrorDetailsInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorErrorDetailsInnerJsonConverter" /> class.
        /// </summary>
        public ErrorErrorDetailsInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ErrorErrorDetailsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ErrorErrorDetailsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> field = default;
            Option<string?> code = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "field":
                            field = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!field.IsSet)
                throw new ArgumentException("Property is required for class ErrorErrorDetailsInner.", nameof(field));

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class ErrorErrorDetailsInner.", nameof(code));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class ErrorErrorDetailsInner.", nameof(message));

            if (field.IsSet && field.Value == null)
                throw new ArgumentNullException(nameof(field), "Property is not nullable for class ErrorErrorDetailsInner.");

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class ErrorErrorDetailsInner.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class ErrorErrorDetailsInner.");

            return new ErrorErrorDetailsInner(field.Value!, code.Value!, message.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ErrorErrorDetailsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="errorErrorDetailsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ErrorErrorDetailsInner errorErrorDetailsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, errorErrorDetailsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ErrorErrorDetailsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="errorErrorDetailsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ErrorErrorDetailsInner errorErrorDetailsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (errorErrorDetailsInner.Field == null)
                throw new ArgumentNullException(nameof(errorErrorDetailsInner.Field), "Property is required for class ErrorErrorDetailsInner.");

            if (errorErrorDetailsInner.Code == null)
                throw new ArgumentNullException(nameof(errorErrorDetailsInner.Code), "Property is required for class ErrorErrorDetailsInner.");

            if (errorErrorDetailsInner.Message == null)
                throw new ArgumentNullException(nameof(errorErrorDetailsInner.Message), "Property is required for class ErrorErrorDetailsInner.");

            writer.WriteString("field", errorErrorDetailsInner.Field);

            writer.WriteString("code", errorErrorDetailsInner.Code);

            writer.WriteString("message", errorErrorDetailsInner.Message);
        }
    }
}
