// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// ErrorError
    /// </summary>
    public partial class ErrorError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorError" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="code">code</param>
        /// <param name="message">message</param>
        /// <param name="requestId">requestId</param>
        /// <param name="details">details</param>
        [JsonConstructor]
        public ErrorError(string type, string code, string message, string requestId, Option<List<ErrorErrorDetailsInner>?> details = default)
        {
            Type = type;
            Code = code;
            Message = message;
            RequestId = requestId;
            DetailsOption = details;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>
        [JsonPropertyName("requestId")]
        public string RequestId { get; set; }

        /// <summary>
        /// Used to track the state of Details
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ErrorErrorDetailsInner>?> DetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [JsonPropertyName("details")]
        public List<ErrorErrorDetailsInner>? Details { get { return this.DetailsOption.Value; } set { this.DetailsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ErrorError {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ErrorError" />
    /// </summary>
    public partial class ErrorErrorJsonConverter : JsonConverter<ErrorError>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorErrorJsonConverter" /> class.
        /// </summary>
        public ErrorErrorJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ErrorError" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ErrorError Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> type = default;
            Option<string?> code = default;
            Option<string?> message = default;
            Option<string?> requestId = default;
            Option<List<ErrorErrorDetailsInner>?> details = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "requestId":
                            requestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "details":
                            details = new Option<List<ErrorErrorDetailsInner>?>(JsonSerializer.Deserialize<List<ErrorErrorDetailsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class ErrorError.", nameof(type));

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class ErrorError.", nameof(code));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class ErrorError.", nameof(message));

            if (!requestId.IsSet)
                throw new ArgumentException("Property is required for class ErrorError.", nameof(requestId));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class ErrorError.");

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class ErrorError.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class ErrorError.");

            if (requestId.IsSet && requestId.Value == null)
                throw new ArgumentNullException(nameof(requestId), "Property is not nullable for class ErrorError.");

            if (details.IsSet && details.Value == null)
                throw new ArgumentNullException(nameof(details), "Property is not nullable for class ErrorError.");

            return new ErrorError(type.Value!, code.Value!, message.Value!, requestId.Value!, details);
        }

        /// <summary>
        /// Serializes a <see cref="ErrorError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="errorError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ErrorError errorError, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, errorError, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ErrorError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="errorError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ErrorError errorError, JsonSerializerOptions jsonSerializerOptions)
        {
            if (errorError.Type == null)
                throw new ArgumentNullException(nameof(errorError.Type), "Property is required for class ErrorError.");

            if (errorError.Code == null)
                throw new ArgumentNullException(nameof(errorError.Code), "Property is required for class ErrorError.");

            if (errorError.Message == null)
                throw new ArgumentNullException(nameof(errorError.Message), "Property is required for class ErrorError.");

            if (errorError.RequestId == null)
                throw new ArgumentNullException(nameof(errorError.RequestId), "Property is required for class ErrorError.");

            if (errorError.DetailsOption.IsSet && errorError.Details == null)
                throw new ArgumentNullException(nameof(errorError.Details), "Property is required for class ErrorError.");

            writer.WriteString("type", errorError.Type);

            writer.WriteString("code", errorError.Code);

            writer.WriteString("message", errorError.Message);

            writer.WriteString("requestId", errorError.RequestId);

            if (errorError.DetailsOption.IsSet)
            {
                writer.WritePropertyName("details");
                JsonSerializer.Serialize(writer, errorError.Details, jsonSerializerOptions);
            }
        }
    }
}
