// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// FinalRefund
    /// </summary>
    public partial class FinalRefund : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FinalRefund" /> class.
        /// </summary>
        /// <param name="paymentId">paymentId</param>
        /// <param name="amount">Сумма в копейках.</param>
        /// <param name="currency">currency</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="reason">reason</param>
        /// <param name="failureCode">failureCode</param>
        /// <param name="failureMessage">failureMessage</param>
        /// <param name="acceptedAt">acceptedAt</param>
        /// <param name="declinedAt">declinedAt</param>
        [JsonConstructor]
        public FinalRefund(Guid paymentId, int amount, CurrencyEnum currency, StatusEnum status, DateTime createdAt, DateTime updatedAt, Option<string?> reason = default, Option<string?> failureCode = default, Option<string?> failureMessage = default, Option<DateTime?> acceptedAt = default, Option<DateTime?> declinedAt = default)
        {
            PaymentId = paymentId;
            Amount = amount;
            Currency = currency;
            Status = status;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            ReasonOption = reason;
            FailureCodeOption = failureCode;
            FailureMessageOption = failureMessage;
            AcceptedAtOption = acceptedAt;
            DeclinedAtOption = declinedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Currency
        /// </summary>
        public enum CurrencyEnum
        {
            /// <summary>
            /// Enum RUB for value: RUB
            /// </summary>
            RUB = 1
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CurrencyEnum CurrencyEnumFromString(string value)
        {
            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            throw new NotImplementedException($"Could not convert value to type CurrencyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CurrencyEnum? CurrencyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CurrencyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CurrencyEnumToJsonValue(CurrencyEnum value)
        {
            if (value == CurrencyEnum.RUB)
                return "RUB";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public CurrencyEnum Currency { get; set; }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Accepted for value: accepted
            /// </summary>
            Accepted = 1,

            /// <summary>
            /// Enum Declined for value: declined
            /// </summary>
            Declined = 2
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("accepted"))
                return StatusEnum.Accepted;

            if (value.Equals("declined"))
                return StatusEnum.Declined;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("accepted"))
                return StatusEnum.Accepted;

            if (value.Equals("declined"))
                return StatusEnum.Declined;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Accepted)
                return "accepted";

            if (value == StatusEnum.Declined)
                return "declined";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets PaymentId
        /// </summary>
        [JsonPropertyName("paymentId")]
        public Guid PaymentId { get; set; }

        /// <summary>
        /// Сумма в копейках.
        /// </summary>
        /// <value>Сумма в копейках.</value>
        [JsonPropertyName("amount")]
        public int Amount { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of Reason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [JsonPropertyName("reason")]
        public string? Reason { get { return this.ReasonOption.Value; } set { this.ReasonOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailureCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FailureCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailureCode
        /// </summary>
        [JsonPropertyName("failureCode")]
        public string? FailureCode { get { return this.FailureCodeOption.Value; } set { this.FailureCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailureMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FailureMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailureMessage
        /// </summary>
        [JsonPropertyName("failureMessage")]
        public string? FailureMessage { get { return this.FailureMessageOption.Value; } set { this.FailureMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of AcceptedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> AcceptedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets AcceptedAt
        /// </summary>
        [JsonPropertyName("acceptedAt")]
        public DateTime? AcceptedAt { get { return this.AcceptedAtOption.Value; } set { this.AcceptedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of DeclinedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DeclinedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets DeclinedAt
        /// </summary>
        [JsonPropertyName("declinedAt")]
        public DateTime? DeclinedAt { get { return this.DeclinedAtOption.Value; } set { this.DeclinedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FinalRefund {\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  FailureCode: ").Append(FailureCode).Append("\n");
            sb.Append("  FailureMessage: ").Append(FailureMessage).Append("\n");
            sb.Append("  AcceptedAt: ").Append(AcceptedAt).Append("\n");
            sb.Append("  DeclinedAt: ").Append(DeclinedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Amount (int) minimum
            if (this.Amount < (int)1)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 1.", new [] { "Amount" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FinalRefund" />
    /// </summary>
    public partial class FinalRefundJsonConverter : JsonConverter<FinalRefund>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="FinalRefundJsonConverter" /> class.
        /// </summary>
        public FinalRefundJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize AcceptedAt
        /// </summary>
        public string AcceptedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DeclinedAt
        /// </summary>
        public string DeclinedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="FinalRefund" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FinalRefund Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> paymentId = default;
            Option<int?> amount = default;
            Option<FinalRefund.CurrencyEnum?> currency = default;
            Option<FinalRefund.StatusEnum?> status = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> reason = default;
            Option<string?> failureCode = default;
            Option<string?> failureMessage = default;
            Option<DateTime?> acceptedAt = default;
            Option<DateTime?> declinedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "paymentId":
                            paymentId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "amount":
                            amount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "currency":
                            string? currencyRawValue = utf8JsonReader.GetString();
                            if (currencyRawValue != null)
                            {
                                FinalRefund.CurrencyEnum? currencyValue = FinalRefund.CurrencyEnumFromStringOrDefault(currencyRawValue);
                                if (currencyValue == null)
                                    throw new JsonException();
                                currency = new Option<FinalRefund.CurrencyEnum?>(currencyValue);
                            }
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                FinalRefund.StatusEnum? statusValue = FinalRefund.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<FinalRefund.StatusEnum?>(statusValue);
                            }
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "reason":
                            reason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "failureCode":
                            failureCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "failureMessage":
                            failureMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "acceptedAt":
                            acceptedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "declinedAt":
                            declinedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!paymentId.IsSet)
                throw new ArgumentException("Property is required for class FinalRefund.", nameof(paymentId));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class FinalRefund.", nameof(amount));

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class FinalRefund.", nameof(currency));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class FinalRefund.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class FinalRefund.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class FinalRefund.", nameof(updatedAt));

            if (paymentId.IsSet && paymentId.Value == null)
                throw new ArgumentNullException(nameof(paymentId), "Property is not nullable for class FinalRefund.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class FinalRefund.");

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class FinalRefund.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class FinalRefund.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class FinalRefund.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class FinalRefund.");

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class FinalRefund.");

            if (failureCode.IsSet && failureCode.Value == null)
                throw new ArgumentNullException(nameof(failureCode), "Property is not nullable for class FinalRefund.");

            if (failureMessage.IsSet && failureMessage.Value == null)
                throw new ArgumentNullException(nameof(failureMessage), "Property is not nullable for class FinalRefund.");

            if (acceptedAt.IsSet && acceptedAt.Value == null)
                throw new ArgumentNullException(nameof(acceptedAt), "Property is not nullable for class FinalRefund.");

            if (declinedAt.IsSet && declinedAt.Value == null)
                throw new ArgumentNullException(nameof(declinedAt), "Property is not nullable for class FinalRefund.");

            return new FinalRefund(paymentId.Value!.Value!, amount.Value!.Value!, currency.Value!.Value!, status.Value!.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, reason, failureCode, failureMessage, acceptedAt, declinedAt);
        }

        /// <summary>
        /// Serializes a <see cref="FinalRefund" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="finalRefund"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FinalRefund finalRefund, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, finalRefund, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FinalRefund" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="finalRefund"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FinalRefund finalRefund, JsonSerializerOptions jsonSerializerOptions)
        {
            if (finalRefund.ReasonOption.IsSet && finalRefund.Reason == null)
                throw new ArgumentNullException(nameof(finalRefund.Reason), "Property is required for class FinalRefund.");

            if (finalRefund.FailureCodeOption.IsSet && finalRefund.FailureCode == null)
                throw new ArgumentNullException(nameof(finalRefund.FailureCode), "Property is required for class FinalRefund.");

            if (finalRefund.FailureMessageOption.IsSet && finalRefund.FailureMessage == null)
                throw new ArgumentNullException(nameof(finalRefund.FailureMessage), "Property is required for class FinalRefund.");

            writer.WriteString("paymentId", finalRefund.PaymentId);

            writer.WriteNumber("amount", finalRefund.Amount);

            var currencyRawValue = FinalRefund.CurrencyEnumToJsonValue(finalRefund.Currency);
            writer.WriteString("currency", currencyRawValue);
            var statusRawValue = FinalRefund.StatusEnumToJsonValue(finalRefund.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteString("createdAt", finalRefund.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updatedAt", finalRefund.UpdatedAt.ToString(UpdatedAtFormat));

            if (finalRefund.ReasonOption.IsSet)
                writer.WriteString("reason", finalRefund.Reason);

            if (finalRefund.FailureCodeOption.IsSet)
                writer.WriteString("failureCode", finalRefund.FailureCode);

            if (finalRefund.FailureMessageOption.IsSet)
                writer.WriteString("failureMessage", finalRefund.FailureMessage);

            if (finalRefund.AcceptedAtOption.IsSet)
                writer.WriteString("acceptedAt", finalRefund.AcceptedAtOption.Value!.Value.ToString(AcceptedAtFormat));

            if (finalRefund.DeclinedAtOption.IsSet)
                writer.WriteString("declinedAt", finalRefund.DeclinedAtOption.Value!.Value.ToString(DeclinedAtFormat));
        }
    }
}
