// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// PaymentDetails
    /// </summary>
    public partial class PaymentDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentDetails" /> class.
        /// </summary>
        /// <param name="paymentId">paymentId</param>
        /// <param name="orderId">orderId</param>
        /// <param name="amount">Сумма в копейках.</param>
        /// <param name="currency">currency</param>
        /// <param name="paymentMethod">paymentMethod</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="description">description</param>
        /// <param name="paymentUrl">Адрес оплаты для платежа в статусе pending.</param>
        /// <param name="failureCode">failureCode</param>
        /// <param name="failureMessage">Нормализованное сообщение, безопасное для показа мерчанту; никогда не содержит сырой ответ провайдера, credentials или данные карты.</param>
        /// <param name="refundSummary">refundSummary</param>
        /// <param name="completedAt">completedAt</param>
        /// <param name="refunds">Устарело, так как список неограничен. Используйте GET /payments/{paymentId}/refunds.</param>
        [JsonConstructor]
        public PaymentDetails(Guid paymentId, string orderId, int amount, CurrencyEnum currency, PaymentMethodEnum paymentMethod, StatusEnum status, DateTime createdAt, DateTime updatedAt, Option<string?> description = default, Option<string?> paymentUrl = default, Option<string?> failureCode = default, Option<string?> failureMessage = default, Option<RefundSummary?> refundSummary = default, Option<DateTime?> completedAt = default, Option<List<Refund>?> refunds = default)
        {
            PaymentId = paymentId;
            OrderId = orderId;
            Amount = amount;
            Currency = currency;
            PaymentMethod = paymentMethod;
            Status = status;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            DescriptionOption = description;
            PaymentUrlOption = paymentUrl;
            FailureCodeOption = failureCode;
            FailureMessageOption = failureMessage;
            RefundSummaryOption = refundSummary;
            CompletedAtOption = completedAt;
            RefundsOption = refunds;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Currency
        /// </summary>
        public enum CurrencyEnum
        {
            /// <summary>
            /// Enum RUB for value: RUB
            /// </summary>
            RUB = 1
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CurrencyEnum CurrencyEnumFromString(string value)
        {
            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            throw new NotImplementedException($"Could not convert value to type CurrencyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CurrencyEnum? CurrencyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CurrencyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CurrencyEnumToJsonValue(CurrencyEnum value)
        {
            if (value == CurrencyEnum.RUB)
                return "RUB";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public CurrencyEnum Currency { get; set; }

        /// <summary>
        /// Defines PaymentMethod
        /// </summary>
        public enum PaymentMethodEnum
        {
            /// <summary>
            /// Enum Sbp for value: sbp
            /// </summary>
            Sbp = 1,

            /// <summary>
            /// Enum Tpay for value: tpay
            /// </summary>
            Tpay = 2
        }

        /// <summary>
        /// Returns a <see cref="PaymentMethodEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static PaymentMethodEnum PaymentMethodEnumFromString(string value)
        {
            if (value.Equals("sbp"))
                return PaymentMethodEnum.Sbp;

            if (value.Equals("tpay"))
                return PaymentMethodEnum.Tpay;

            throw new NotImplementedException($"Could not convert value to type PaymentMethodEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="PaymentMethodEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PaymentMethodEnum? PaymentMethodEnumFromStringOrDefault(string value)
        {
            if (value.Equals("sbp"))
                return PaymentMethodEnum.Sbp;

            if (value.Equals("tpay"))
                return PaymentMethodEnum.Tpay;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="PaymentMethodEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string PaymentMethodEnumToJsonValue(PaymentMethodEnum value)
        {
            if (value == PaymentMethodEnum.Sbp)
                return "sbp";

            if (value == PaymentMethodEnum.Tpay)
                return "tpay";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets PaymentMethod
        /// </summary>
        [JsonPropertyName("paymentMethod")]
        public PaymentMethodEnum PaymentMethod { get; set; }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 1,

            /// <summary>
            /// Enum Succeeded for value: succeeded
            /// </summary>
            Succeeded = 2,

            /// <summary>
            /// Enum Cancelled for value: cancelled
            /// </summary>
            Cancelled = 3,

            /// <summary>
            /// Enum Chargebacked for value: chargebacked
            /// </summary>
            Chargebacked = 4,

            /// <summary>
            /// Enum Refunded for value: refunded
            /// </summary>
            Refunded = 5
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("succeeded"))
                return StatusEnum.Succeeded;

            if (value.Equals("cancelled"))
                return StatusEnum.Cancelled;

            if (value.Equals("chargebacked"))
                return StatusEnum.Chargebacked;

            if (value.Equals("refunded"))
                return StatusEnum.Refunded;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("succeeded"))
                return StatusEnum.Succeeded;

            if (value.Equals("cancelled"))
                return StatusEnum.Cancelled;

            if (value.Equals("chargebacked"))
                return StatusEnum.Chargebacked;

            if (value.Equals("refunded"))
                return StatusEnum.Refunded;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Pending)
                return "pending";

            if (value == StatusEnum.Succeeded)
                return "succeeded";

            if (value == StatusEnum.Cancelled)
                return "cancelled";

            if (value == StatusEnum.Chargebacked)
                return "chargebacked";

            if (value == StatusEnum.Refunded)
                return "refunded";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets PaymentId
        /// </summary>
        [JsonPropertyName("paymentId")]
        public Guid PaymentId { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [JsonPropertyName("orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// Сумма в копейках.
        /// </summary>
        /// <value>Сумма в копейках.</value>
        [JsonPropertyName("amount")]
        public int Amount { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PaymentUrlOption { get; private set; }

        /// <summary>
        /// Адрес оплаты для платежа в статусе pending.
        /// </summary>
        /// <value>Адрес оплаты для платежа в статусе pending.</value>
        [JsonPropertyName("paymentUrl")]
        public string? PaymentUrl { get { return this.PaymentUrlOption.Value; } set { this.PaymentUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailureCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FailureCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailureCode
        /// </summary>
        [JsonPropertyName("failureCode")]
        public string? FailureCode { get { return this.FailureCodeOption.Value; } set { this.FailureCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailureMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FailureMessageOption { get; private set; }

        /// <summary>
        /// Нормализованное сообщение, безопасное для показа мерчанту; никогда не содержит сырой ответ провайдера, credentials или данные карты.
        /// </summary>
        /// <value>Нормализованное сообщение, безопасное для показа мерчанту; никогда не содержит сырой ответ провайдера, credentials или данные карты.</value>
        [JsonPropertyName("failureMessage")]
        public string? FailureMessage { get { return this.FailureMessageOption.Value; } set { this.FailureMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of RefundSummary
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RefundSummary?> RefundSummaryOption { get; private set; }

        /// <summary>
        /// Gets or Sets RefundSummary
        /// </summary>
        [JsonPropertyName("refundSummary")]
        public RefundSummary? RefundSummary { get { return this.RefundSummaryOption.Value; } set { this.RefundSummaryOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompletedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CompletedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [JsonPropertyName("completedAt")]
        public DateTime? CompletedAt { get { return this.CompletedAtOption.Value; } set { this.CompletedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Refunds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Refund>?> RefundsOption { get; private set; }

        /// <summary>
        /// Устарело, так как список неограничен. Используйте GET /payments/{paymentId}/refunds.
        /// </summary>
        /// <value>Устарело, так как список неограничен. Используйте GET /payments/{paymentId}/refunds.</value>
        [JsonPropertyName("refunds")]
        [Obsolete]
        public List<Refund>? Refunds { get { return this.RefundsOption.Value; } set { this.RefundsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentDetails {\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  PaymentUrl: ").Append(PaymentUrl).Append("\n");
            sb.Append("  FailureCode: ").Append(FailureCode).Append("\n");
            sb.Append("  FailureMessage: ").Append(FailureMessage).Append("\n");
            sb.Append("  RefundSummary: ").Append(RefundSummary).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("  Refunds: ").Append(Refunds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Amount (int) minimum
            if (this.Amount < (int)1)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 1.", new [] { "Amount" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 255.", new [] { "Description" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaymentDetails" />
    /// </summary>
    public partial class PaymentDetailsJsonConverter : JsonConverter<PaymentDetails>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentDetailsJsonConverter" /> class.
        /// </summary>
        public PaymentDetailsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public string CompletedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="PaymentDetails" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaymentDetails Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> paymentId = default;
            Option<string?> orderId = default;
            Option<int?> amount = default;
            Option<PaymentDetails.CurrencyEnum?> currency = default;
            Option<PaymentDetails.PaymentMethodEnum?> paymentMethod = default;
            Option<PaymentDetails.StatusEnum?> status = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> description = default;
            Option<string?> paymentUrl = default;
            Option<string?> failureCode = default;
            Option<string?> failureMessage = default;
            Option<RefundSummary?> refundSummary = default;
            Option<DateTime?> completedAt = default;
            Option<List<Refund>?> refunds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "paymentId":
                            paymentId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "orderId":
                            orderId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "currency":
                            string? currencyRawValue = utf8JsonReader.GetString();
                            if (currencyRawValue != null)
                            {
                                PaymentDetails.CurrencyEnum? currencyValue = PaymentDetails.CurrencyEnumFromStringOrDefault(currencyRawValue);
                                if (currencyValue == null)
                                    throw new JsonException();
                                currency = new Option<PaymentDetails.CurrencyEnum?>(currencyValue);
                            }
                            break;
                        case "paymentMethod":
                            string? paymentMethodRawValue = utf8JsonReader.GetString();
                            if (paymentMethodRawValue != null)
                            {
                                PaymentDetails.PaymentMethodEnum? paymentMethodValue = PaymentDetails.PaymentMethodEnumFromStringOrDefault(paymentMethodRawValue);
                                if (paymentMethodValue == null)
                                    throw new JsonException();
                                paymentMethod = new Option<PaymentDetails.PaymentMethodEnum?>(paymentMethodValue);
                            }
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                PaymentDetails.StatusEnum? statusValue = PaymentDetails.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<PaymentDetails.StatusEnum?>(statusValue);
                            }
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "paymentUrl":
                            paymentUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "failureCode":
                            failureCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "failureMessage":
                            failureMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "refundSummary":
                            refundSummary = new Option<RefundSummary?>(JsonSerializer.Deserialize<RefundSummary>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "completedAt":
                            completedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "refunds":
                            refunds = new Option<List<Refund>?>(JsonSerializer.Deserialize<List<Refund>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!paymentId.IsSet)
                throw new ArgumentException("Property is required for class PaymentDetails.", nameof(paymentId));

            if (!orderId.IsSet)
                throw new ArgumentException("Property is required for class PaymentDetails.", nameof(orderId));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class PaymentDetails.", nameof(amount));

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class PaymentDetails.", nameof(currency));

            if (!paymentMethod.IsSet)
                throw new ArgumentException("Property is required for class PaymentDetails.", nameof(paymentMethod));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class PaymentDetails.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class PaymentDetails.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class PaymentDetails.", nameof(updatedAt));

            if (paymentId.IsSet && paymentId.Value == null)
                throw new ArgumentNullException(nameof(paymentId), "Property is not nullable for class PaymentDetails.");

            if (orderId.IsSet && orderId.Value == null)
                throw new ArgumentNullException(nameof(orderId), "Property is not nullable for class PaymentDetails.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class PaymentDetails.");

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class PaymentDetails.");

            if (paymentMethod.IsSet && paymentMethod.Value == null)
                throw new ArgumentNullException(nameof(paymentMethod), "Property is not nullable for class PaymentDetails.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class PaymentDetails.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class PaymentDetails.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class PaymentDetails.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class PaymentDetails.");

            if (paymentUrl.IsSet && paymentUrl.Value == null)
                throw new ArgumentNullException(nameof(paymentUrl), "Property is not nullable for class PaymentDetails.");

            if (failureCode.IsSet && failureCode.Value == null)
                throw new ArgumentNullException(nameof(failureCode), "Property is not nullable for class PaymentDetails.");

            if (failureMessage.IsSet && failureMessage.Value == null)
                throw new ArgumentNullException(nameof(failureMessage), "Property is not nullable for class PaymentDetails.");

            if (refundSummary.IsSet && refundSummary.Value == null)
                throw new ArgumentNullException(nameof(refundSummary), "Property is not nullable for class PaymentDetails.");

            if (completedAt.IsSet && completedAt.Value == null)
                throw new ArgumentNullException(nameof(completedAt), "Property is not nullable for class PaymentDetails.");

            if (refunds.IsSet && refunds.Value == null)
                throw new ArgumentNullException(nameof(refunds), "Property is not nullable for class PaymentDetails.");

            return new PaymentDetails(paymentId.Value!.Value!, orderId.Value!, amount.Value!.Value!, currency.Value!.Value!, paymentMethod.Value!.Value!, status.Value!.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, description, paymentUrl, failureCode, failureMessage, refundSummary, completedAt, refunds);
        }

        /// <summary>
        /// Serializes a <see cref="PaymentDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaymentDetails paymentDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paymentDetails, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaymentDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaymentDetails paymentDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            if (paymentDetails.OrderId == null)
                throw new ArgumentNullException(nameof(paymentDetails.OrderId), "Property is required for class PaymentDetails.");

            if (paymentDetails.DescriptionOption.IsSet && paymentDetails.Description == null)
                throw new ArgumentNullException(nameof(paymentDetails.Description), "Property is required for class PaymentDetails.");

            if (paymentDetails.PaymentUrlOption.IsSet && paymentDetails.PaymentUrl == null)
                throw new ArgumentNullException(nameof(paymentDetails.PaymentUrl), "Property is required for class PaymentDetails.");

            if (paymentDetails.FailureCodeOption.IsSet && paymentDetails.FailureCode == null)
                throw new ArgumentNullException(nameof(paymentDetails.FailureCode), "Property is required for class PaymentDetails.");

            if (paymentDetails.FailureMessageOption.IsSet && paymentDetails.FailureMessage == null)
                throw new ArgumentNullException(nameof(paymentDetails.FailureMessage), "Property is required for class PaymentDetails.");

            if (paymentDetails.RefundSummaryOption.IsSet && paymentDetails.RefundSummary == null)
                throw new ArgumentNullException(nameof(paymentDetails.RefundSummary), "Property is required for class PaymentDetails.");

            if (paymentDetails.RefundsOption.IsSet && paymentDetails.Refunds == null)
                throw new ArgumentNullException(nameof(paymentDetails.Refunds), "Property is required for class PaymentDetails.");

            writer.WriteString("paymentId", paymentDetails.PaymentId);

            writer.WriteString("orderId", paymentDetails.OrderId);

            writer.WriteNumber("amount", paymentDetails.Amount);

            var currencyRawValue = PaymentDetails.CurrencyEnumToJsonValue(paymentDetails.Currency);
            writer.WriteString("currency", currencyRawValue);
            var paymentMethodRawValue = PaymentDetails.PaymentMethodEnumToJsonValue(paymentDetails.PaymentMethod);
            writer.WriteString("paymentMethod", paymentMethodRawValue);
            var statusRawValue = PaymentDetails.StatusEnumToJsonValue(paymentDetails.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteString("createdAt", paymentDetails.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updatedAt", paymentDetails.UpdatedAt.ToString(UpdatedAtFormat));

            if (paymentDetails.DescriptionOption.IsSet)
                writer.WriteString("description", paymentDetails.Description);

            if (paymentDetails.PaymentUrlOption.IsSet)
                writer.WriteString("paymentUrl", paymentDetails.PaymentUrl);

            if (paymentDetails.FailureCodeOption.IsSet)
                writer.WriteString("failureCode", paymentDetails.FailureCode);

            if (paymentDetails.FailureMessageOption.IsSet)
                writer.WriteString("failureMessage", paymentDetails.FailureMessage);

            if (paymentDetails.RefundSummaryOption.IsSet)
            {
                writer.WritePropertyName("refundSummary");
                JsonSerializer.Serialize(writer, paymentDetails.RefundSummary, jsonSerializerOptions);
            }
            if (paymentDetails.CompletedAtOption.IsSet)
                writer.WriteString("completedAt", paymentDetails.CompletedAtOption.Value!.Value.ToString(CompletedAtFormat));

            if (paymentDetails.RefundsOption.IsSet)
            {
                writer.WritePropertyName("refunds");
                JsonSerializer.Serialize(writer, paymentDetails.Refunds, jsonSerializerOptions);
            }
        }
    }
}
