// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// PostpaymentWebhookNotification
    /// </summary>
    public partial class PostpaymentWebhookNotification : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostpaymentWebhookNotification" /> class.
        /// </summary>
        /// <param name="notificationId">notificationId</param>
        /// <param name="notificationType">notificationType</param>
        /// <param name="notificationDate">notificationDate</param>
        /// <param name="payment">payment</param>
        [JsonConstructor]
        public PostpaymentWebhookNotification(Guid notificationId, NotificationTypeEnum notificationType, DateTime notificationDate, FinalPayment payment)
        {
            NotificationId = notificationId;
            NotificationType = notificationType;
            NotificationDate = notificationDate;
            Payment = payment;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines NotificationType
        /// </summary>
        public enum NotificationTypeEnum
        {
            /// <summary>
            /// Enum Postpayment for value: postpayment
            /// </summary>
            Postpayment = 1
        }

        /// <summary>
        /// Returns a <see cref="NotificationTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static NotificationTypeEnum NotificationTypeEnumFromString(string value)
        {
            if (value.Equals("postpayment"))
                return NotificationTypeEnum.Postpayment;

            throw new NotImplementedException($"Could not convert value to type NotificationTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="NotificationTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NotificationTypeEnum? NotificationTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("postpayment"))
                return NotificationTypeEnum.Postpayment;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="NotificationTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string NotificationTypeEnumToJsonValue(NotificationTypeEnum value)
        {
            if (value == NotificationTypeEnum.Postpayment)
                return "postpayment";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets NotificationType
        /// </summary>
        [JsonPropertyName("notificationType")]
        public NotificationTypeEnum NotificationType { get; set; }

        /// <summary>
        /// Gets or Sets NotificationId
        /// </summary>
        [JsonPropertyName("notificationId")]
        public Guid NotificationId { get; set; }

        /// <summary>
        /// Gets or Sets NotificationDate
        /// </summary>
        [JsonPropertyName("notificationDate")]
        public DateTime NotificationDate { get; set; }

        /// <summary>
        /// Gets or Sets Payment
        /// </summary>
        [JsonPropertyName("payment")]
        public FinalPayment Payment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostpaymentWebhookNotification {\n");
            sb.Append("  NotificationId: ").Append(NotificationId).Append("\n");
            sb.Append("  NotificationType: ").Append(NotificationType).Append("\n");
            sb.Append("  NotificationDate: ").Append(NotificationDate).Append("\n");
            sb.Append("  Payment: ").Append(Payment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostpaymentWebhookNotification" />
    /// </summary>
    public partial class PostpaymentWebhookNotificationJsonConverter : JsonConverter<PostpaymentWebhookNotification>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PostpaymentWebhookNotificationJsonConverter" /> class.
        /// </summary>
        public PostpaymentWebhookNotificationJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize NotificationDate
        /// </summary>
        public string NotificationDateFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="PostpaymentWebhookNotification" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostpaymentWebhookNotification Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> notificationId = default;
            Option<PostpaymentWebhookNotification.NotificationTypeEnum?> notificationType = default;
            Option<DateTime?> notificationDate = default;
            Option<FinalPayment?> payment = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "notificationId":
                            notificationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "notificationType":
                            string? notificationTypeRawValue = utf8JsonReader.GetString();
                            if (notificationTypeRawValue != null)
                            {
                                PostpaymentWebhookNotification.NotificationTypeEnum? notificationTypeValue = PostpaymentWebhookNotification.NotificationTypeEnumFromStringOrDefault(notificationTypeRawValue);
                                if (notificationTypeValue == null)
                                    throw new JsonException();
                                notificationType = new Option<PostpaymentWebhookNotification.NotificationTypeEnum?>(notificationTypeValue);
                            }
                            break;
                        case "notificationDate":
                            notificationDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "payment":
                            payment = new Option<FinalPayment?>(JsonSerializer.Deserialize<FinalPayment>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!notificationId.IsSet)
                throw new ArgumentException("Property is required for class PostpaymentWebhookNotification.", nameof(notificationId));

            if (!notificationType.IsSet)
                throw new ArgumentException("Property is required for class PostpaymentWebhookNotification.", nameof(notificationType));

            if (!notificationDate.IsSet)
                throw new ArgumentException("Property is required for class PostpaymentWebhookNotification.", nameof(notificationDate));

            if (!payment.IsSet)
                throw new ArgumentException("Property is required for class PostpaymentWebhookNotification.", nameof(payment));

            if (notificationId.IsSet && notificationId.Value == null)
                throw new ArgumentNullException(nameof(notificationId), "Property is not nullable for class PostpaymentWebhookNotification.");

            if (notificationType.IsSet && notificationType.Value == null)
                throw new ArgumentNullException(nameof(notificationType), "Property is not nullable for class PostpaymentWebhookNotification.");

            if (notificationDate.IsSet && notificationDate.Value == null)
                throw new ArgumentNullException(nameof(notificationDate), "Property is not nullable for class PostpaymentWebhookNotification.");

            if (payment.IsSet && payment.Value == null)
                throw new ArgumentNullException(nameof(payment), "Property is not nullable for class PostpaymentWebhookNotification.");

            return new PostpaymentWebhookNotification(notificationId.Value!.Value!, notificationType.Value!.Value!, notificationDate.Value!.Value!, payment.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PostpaymentWebhookNotification" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postpaymentWebhookNotification"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostpaymentWebhookNotification postpaymentWebhookNotification, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postpaymentWebhookNotification, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostpaymentWebhookNotification" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postpaymentWebhookNotification"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostpaymentWebhookNotification postpaymentWebhookNotification, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postpaymentWebhookNotification.Payment == null)
                throw new ArgumentNullException(nameof(postpaymentWebhookNotification.Payment), "Property is required for class PostpaymentWebhookNotification.");

            writer.WriteString("notificationId", postpaymentWebhookNotification.NotificationId);

            var notificationTypeRawValue = PostpaymentWebhookNotification.NotificationTypeEnumToJsonValue(postpaymentWebhookNotification.NotificationType);
            writer.WriteString("notificationType", notificationTypeRawValue);
            writer.WriteString("notificationDate", postpaymentWebhookNotification.NotificationDate.ToString(NotificationDateFormat));

            writer.WritePropertyName("payment");
            JsonSerializer.Serialize(writer, postpaymentWebhookNotification.Payment, jsonSerializerOptions);
        }
    }
}
