// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// PrepaymentPayment
    /// </summary>
    public partial class PrepaymentPayment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrepaymentPayment" /> class.
        /// </summary>
        /// <param name="paymentId">paymentId</param>
        /// <param name="orderId">orderId</param>
        /// <param name="amount">Сумма в копейках.</param>
        /// <param name="currency">currency</param>
        /// <param name="paymentMethod">paymentMethod</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="description">description</param>
        /// <param name="paymentUrl">Адрес оплаты для платежа в статусе pending.</param>
        /// <param name="expiresAt">expiresAt</param>
        /// <param name="failureCode">failureCode</param>
        /// <param name="failureMessage">failureMessage</param>
        /// <param name="completedAt">completedAt</param>
        [JsonConstructor]
        public PrepaymentPayment(Guid paymentId, string orderId, int amount, CurrencyEnum currency, PaymentMethodEnum paymentMethod, StatusEnum status, DateTime createdAt, DateTime updatedAt, Option<string?> description = default, Option<string?> paymentUrl = default, Option<DateTime?> expiresAt = default, Option<string?> failureCode = default, Option<string?> failureMessage = default, Option<DateTime?> completedAt = default)
        {
            PaymentId = paymentId;
            OrderId = orderId;
            Amount = amount;
            Currency = currency;
            PaymentMethod = paymentMethod;
            Status = status;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            DescriptionOption = description;
            PaymentUrlOption = paymentUrl;
            ExpiresAtOption = expiresAt;
            FailureCodeOption = failureCode;
            FailureMessageOption = failureMessage;
            CompletedAtOption = completedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Currency
        /// </summary>
        public enum CurrencyEnum
        {
            /// <summary>
            /// Enum RUB for value: RUB
            /// </summary>
            RUB = 1
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CurrencyEnum CurrencyEnumFromString(string value)
        {
            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            throw new NotImplementedException($"Could not convert value to type CurrencyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CurrencyEnum? CurrencyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CurrencyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CurrencyEnumToJsonValue(CurrencyEnum value)
        {
            if (value == CurrencyEnum.RUB)
                return "RUB";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public CurrencyEnum Currency { get; set; }

        /// <summary>
        /// Defines PaymentMethod
        /// </summary>
        public enum PaymentMethodEnum
        {
            /// <summary>
            /// Enum Sbp for value: sbp
            /// </summary>
            Sbp = 1,

            /// <summary>
            /// Enum Tpay for value: tpay
            /// </summary>
            Tpay = 2
        }

        /// <summary>
        /// Returns a <see cref="PaymentMethodEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static PaymentMethodEnum PaymentMethodEnumFromString(string value)
        {
            if (value.Equals("sbp"))
                return PaymentMethodEnum.Sbp;

            if (value.Equals("tpay"))
                return PaymentMethodEnum.Tpay;

            throw new NotImplementedException($"Could not convert value to type PaymentMethodEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="PaymentMethodEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PaymentMethodEnum? PaymentMethodEnumFromStringOrDefault(string value)
        {
            if (value.Equals("sbp"))
                return PaymentMethodEnum.Sbp;

            if (value.Equals("tpay"))
                return PaymentMethodEnum.Tpay;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="PaymentMethodEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string PaymentMethodEnumToJsonValue(PaymentMethodEnum value)
        {
            if (value == PaymentMethodEnum.Sbp)
                return "sbp";

            if (value == PaymentMethodEnum.Tpay)
                return "tpay";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets PaymentMethod
        /// </summary>
        [JsonPropertyName("paymentMethod")]
        public PaymentMethodEnum PaymentMethod { get; set; }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 1
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Pending)
                return "pending";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets PaymentId
        /// </summary>
        [JsonPropertyName("paymentId")]
        public Guid PaymentId { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [JsonPropertyName("orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// Сумма в копейках.
        /// </summary>
        /// <value>Сумма в копейках.</value>
        [JsonPropertyName("amount")]
        public int Amount { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PaymentUrlOption { get; private set; }

        /// <summary>
        /// Адрес оплаты для платежа в статусе pending.
        /// </summary>
        /// <value>Адрес оплаты для платежа в статусе pending.</value>
        [JsonPropertyName("paymentUrl")]
        public string? PaymentUrl { get { return this.PaymentUrlOption.Value; } set { this.PaymentUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpiresAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ExpiresAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [JsonPropertyName("expiresAt")]
        public DateTime? ExpiresAt { get { return this.ExpiresAtOption.Value; } set { this.ExpiresAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailureCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FailureCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailureCode
        /// </summary>
        [JsonPropertyName("failureCode")]
        public string? FailureCode { get { return this.FailureCodeOption.Value; } set { this.FailureCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailureMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FailureMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailureMessage
        /// </summary>
        [JsonPropertyName("failureMessage")]
        public string? FailureMessage { get { return this.FailureMessageOption.Value; } set { this.FailureMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompletedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CompletedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [JsonPropertyName("completedAt")]
        public DateTime? CompletedAt { get { return this.CompletedAtOption.Value; } set { this.CompletedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrepaymentPayment {\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  PaymentUrl: ").Append(PaymentUrl).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  FailureCode: ").Append(FailureCode).Append("\n");
            sb.Append("  FailureMessage: ").Append(FailureMessage).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Amount (int) minimum
            if (this.Amount < (int)1)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 1.", new [] { "Amount" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 255.", new [] { "Description" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PrepaymentPayment" />
    /// </summary>
    public partial class PrepaymentPaymentJsonConverter : JsonConverter<PrepaymentPayment>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PrepaymentPaymentJsonConverter" /> class.
        /// </summary>
        public PrepaymentPaymentJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public string ExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public string CompletedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="PrepaymentPayment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PrepaymentPayment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> paymentId = default;
            Option<string?> orderId = default;
            Option<int?> amount = default;
            Option<PrepaymentPayment.CurrencyEnum?> currency = default;
            Option<PrepaymentPayment.PaymentMethodEnum?> paymentMethod = default;
            Option<PrepaymentPayment.StatusEnum?> status = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> description = default;
            Option<string?> paymentUrl = default;
            Option<DateTime?> expiresAt = default;
            Option<string?> failureCode = default;
            Option<string?> failureMessage = default;
            Option<DateTime?> completedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "paymentId":
                            paymentId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "orderId":
                            orderId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "currency":
                            string? currencyRawValue = utf8JsonReader.GetString();
                            if (currencyRawValue != null)
                            {
                                PrepaymentPayment.CurrencyEnum? currencyValue = PrepaymentPayment.CurrencyEnumFromStringOrDefault(currencyRawValue);
                                if (currencyValue == null)
                                    throw new JsonException();
                                currency = new Option<PrepaymentPayment.CurrencyEnum?>(currencyValue);
                            }
                            break;
                        case "paymentMethod":
                            string? paymentMethodRawValue = utf8JsonReader.GetString();
                            if (paymentMethodRawValue != null)
                            {
                                PrepaymentPayment.PaymentMethodEnum? paymentMethodValue = PrepaymentPayment.PaymentMethodEnumFromStringOrDefault(paymentMethodRawValue);
                                if (paymentMethodValue == null)
                                    throw new JsonException();
                                paymentMethod = new Option<PrepaymentPayment.PaymentMethodEnum?>(paymentMethodValue);
                            }
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                PrepaymentPayment.StatusEnum? statusValue = PrepaymentPayment.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<PrepaymentPayment.StatusEnum?>(statusValue);
                            }
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "paymentUrl":
                            paymentUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expiresAt":
                            expiresAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "failureCode":
                            failureCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "failureMessage":
                            failureMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "completedAt":
                            completedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!paymentId.IsSet)
                throw new ArgumentException("Property is required for class PrepaymentPayment.", nameof(paymentId));

            if (!orderId.IsSet)
                throw new ArgumentException("Property is required for class PrepaymentPayment.", nameof(orderId));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class PrepaymentPayment.", nameof(amount));

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class PrepaymentPayment.", nameof(currency));

            if (!paymentMethod.IsSet)
                throw new ArgumentException("Property is required for class PrepaymentPayment.", nameof(paymentMethod));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class PrepaymentPayment.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class PrepaymentPayment.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class PrepaymentPayment.", nameof(updatedAt));

            if (paymentId.IsSet && paymentId.Value == null)
                throw new ArgumentNullException(nameof(paymentId), "Property is not nullable for class PrepaymentPayment.");

            if (orderId.IsSet && orderId.Value == null)
                throw new ArgumentNullException(nameof(orderId), "Property is not nullable for class PrepaymentPayment.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class PrepaymentPayment.");

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class PrepaymentPayment.");

            if (paymentMethod.IsSet && paymentMethod.Value == null)
                throw new ArgumentNullException(nameof(paymentMethod), "Property is not nullable for class PrepaymentPayment.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class PrepaymentPayment.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class PrepaymentPayment.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class PrepaymentPayment.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class PrepaymentPayment.");

            if (paymentUrl.IsSet && paymentUrl.Value == null)
                throw new ArgumentNullException(nameof(paymentUrl), "Property is not nullable for class PrepaymentPayment.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class PrepaymentPayment.");

            if (failureCode.IsSet && failureCode.Value == null)
                throw new ArgumentNullException(nameof(failureCode), "Property is not nullable for class PrepaymentPayment.");

            if (failureMessage.IsSet && failureMessage.Value == null)
                throw new ArgumentNullException(nameof(failureMessage), "Property is not nullable for class PrepaymentPayment.");

            if (completedAt.IsSet && completedAt.Value == null)
                throw new ArgumentNullException(nameof(completedAt), "Property is not nullable for class PrepaymentPayment.");

            return new PrepaymentPayment(paymentId.Value!.Value!, orderId.Value!, amount.Value!.Value!, currency.Value!.Value!, paymentMethod.Value!.Value!, status.Value!.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, description, paymentUrl, expiresAt, failureCode, failureMessage, completedAt);
        }

        /// <summary>
        /// Serializes a <see cref="PrepaymentPayment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="prepaymentPayment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PrepaymentPayment prepaymentPayment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, prepaymentPayment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PrepaymentPayment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="prepaymentPayment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PrepaymentPayment prepaymentPayment, JsonSerializerOptions jsonSerializerOptions)
        {
            if (prepaymentPayment.OrderId == null)
                throw new ArgumentNullException(nameof(prepaymentPayment.OrderId), "Property is required for class PrepaymentPayment.");

            if (prepaymentPayment.DescriptionOption.IsSet && prepaymentPayment.Description == null)
                throw new ArgumentNullException(nameof(prepaymentPayment.Description), "Property is required for class PrepaymentPayment.");

            if (prepaymentPayment.PaymentUrlOption.IsSet && prepaymentPayment.PaymentUrl == null)
                throw new ArgumentNullException(nameof(prepaymentPayment.PaymentUrl), "Property is required for class PrepaymentPayment.");

            if (prepaymentPayment.FailureCodeOption.IsSet && prepaymentPayment.FailureCode == null)
                throw new ArgumentNullException(nameof(prepaymentPayment.FailureCode), "Property is required for class PrepaymentPayment.");

            if (prepaymentPayment.FailureMessageOption.IsSet && prepaymentPayment.FailureMessage == null)
                throw new ArgumentNullException(nameof(prepaymentPayment.FailureMessage), "Property is required for class PrepaymentPayment.");

            writer.WriteString("paymentId", prepaymentPayment.PaymentId);

            writer.WriteString("orderId", prepaymentPayment.OrderId);

            writer.WriteNumber("amount", prepaymentPayment.Amount);

            var currencyRawValue = PrepaymentPayment.CurrencyEnumToJsonValue(prepaymentPayment.Currency);
            writer.WriteString("currency", currencyRawValue);
            var paymentMethodRawValue = PrepaymentPayment.PaymentMethodEnumToJsonValue(prepaymentPayment.PaymentMethod);
            writer.WriteString("paymentMethod", paymentMethodRawValue);
            var statusRawValue = PrepaymentPayment.StatusEnumToJsonValue(prepaymentPayment.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteString("createdAt", prepaymentPayment.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updatedAt", prepaymentPayment.UpdatedAt.ToString(UpdatedAtFormat));

            if (prepaymentPayment.DescriptionOption.IsSet)
                writer.WriteString("description", prepaymentPayment.Description);

            if (prepaymentPayment.PaymentUrlOption.IsSet)
                writer.WriteString("paymentUrl", prepaymentPayment.PaymentUrl);

            if (prepaymentPayment.ExpiresAtOption.IsSet)
                writer.WriteString("expiresAt", prepaymentPayment.ExpiresAtOption.Value!.Value.ToString(ExpiresAtFormat));

            if (prepaymentPayment.FailureCodeOption.IsSet)
                writer.WriteString("failureCode", prepaymentPayment.FailureCode);

            if (prepaymentPayment.FailureMessageOption.IsSet)
                writer.WriteString("failureMessage", prepaymentPayment.FailureMessage);

            if (prepaymentPayment.CompletedAtOption.IsSet)
                writer.WriteString("completedAt", prepaymentPayment.CompletedAtOption.Value!.Value.ToString(CompletedAtFormat));
        }
    }
}
