// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// RefundWebhookNotification
    /// </summary>
    public partial class RefundWebhookNotification : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundWebhookNotification" /> class.
        /// </summary>
        /// <param name="notificationId">notificationId</param>
        /// <param name="notificationType">notificationType</param>
        /// <param name="notificationDate">notificationDate</param>
        /// <param name="paymentId">paymentId</param>
        /// <param name="refund">refund</param>
        [JsonConstructor]
        public RefundWebhookNotification(Guid notificationId, NotificationTypeEnum notificationType, DateTime notificationDate, Guid paymentId, FinalRefund refund)
        {
            NotificationId = notificationId;
            NotificationType = notificationType;
            NotificationDate = notificationDate;
            PaymentId = paymentId;
            Refund = refund;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines NotificationType
        /// </summary>
        public enum NotificationTypeEnum
        {
            /// <summary>
            /// Enum Refund for value: refund
            /// </summary>
            Refund = 1
        }

        /// <summary>
        /// Returns a <see cref="NotificationTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static NotificationTypeEnum NotificationTypeEnumFromString(string value)
        {
            if (value.Equals("refund"))
                return NotificationTypeEnum.Refund;

            throw new NotImplementedException($"Could not convert value to type NotificationTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="NotificationTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NotificationTypeEnum? NotificationTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("refund"))
                return NotificationTypeEnum.Refund;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="NotificationTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string NotificationTypeEnumToJsonValue(NotificationTypeEnum value)
        {
            if (value == NotificationTypeEnum.Refund)
                return "refund";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets NotificationType
        /// </summary>
        [JsonPropertyName("notificationType")]
        public NotificationTypeEnum NotificationType { get; set; }

        /// <summary>
        /// Gets or Sets NotificationId
        /// </summary>
        [JsonPropertyName("notificationId")]
        public Guid NotificationId { get; set; }

        /// <summary>
        /// Gets or Sets NotificationDate
        /// </summary>
        [JsonPropertyName("notificationDate")]
        public DateTime NotificationDate { get; set; }

        /// <summary>
        /// Gets or Sets PaymentId
        /// </summary>
        [JsonPropertyName("paymentId")]
        public Guid PaymentId { get; set; }

        /// <summary>
        /// Gets or Sets Refund
        /// </summary>
        [JsonPropertyName("refund")]
        public FinalRefund Refund { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RefundWebhookNotification {\n");
            sb.Append("  NotificationId: ").Append(NotificationId).Append("\n");
            sb.Append("  NotificationType: ").Append(NotificationType).Append("\n");
            sb.Append("  NotificationDate: ").Append(NotificationDate).Append("\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  Refund: ").Append(Refund).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RefundWebhookNotification" />
    /// </summary>
    public partial class RefundWebhookNotificationJsonConverter : JsonConverter<RefundWebhookNotification>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="RefundWebhookNotificationJsonConverter" /> class.
        /// </summary>
        public RefundWebhookNotificationJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize NotificationDate
        /// </summary>
        public string NotificationDateFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="RefundWebhookNotification" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RefundWebhookNotification Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> notificationId = default;
            Option<RefundWebhookNotification.NotificationTypeEnum?> notificationType = default;
            Option<DateTime?> notificationDate = default;
            Option<Guid?> paymentId = default;
            Option<FinalRefund?> refund = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "notificationId":
                            notificationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "notificationType":
                            string? notificationTypeRawValue = utf8JsonReader.GetString();
                            if (notificationTypeRawValue != null)
                            {
                                RefundWebhookNotification.NotificationTypeEnum? notificationTypeValue = RefundWebhookNotification.NotificationTypeEnumFromStringOrDefault(notificationTypeRawValue);
                                if (notificationTypeValue == null)
                                    throw new JsonException();
                                notificationType = new Option<RefundWebhookNotification.NotificationTypeEnum?>(notificationTypeValue);
                            }
                            break;
                        case "notificationDate":
                            notificationDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "paymentId":
                            paymentId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "refund":
                            refund = new Option<FinalRefund?>(JsonSerializer.Deserialize<FinalRefund>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!notificationId.IsSet)
                throw new ArgumentException("Property is required for class RefundWebhookNotification.", nameof(notificationId));

            if (!notificationType.IsSet)
                throw new ArgumentException("Property is required for class RefundWebhookNotification.", nameof(notificationType));

            if (!notificationDate.IsSet)
                throw new ArgumentException("Property is required for class RefundWebhookNotification.", nameof(notificationDate));

            if (!paymentId.IsSet)
                throw new ArgumentException("Property is required for class RefundWebhookNotification.", nameof(paymentId));

            if (!refund.IsSet)
                throw new ArgumentException("Property is required for class RefundWebhookNotification.", nameof(refund));

            if (notificationId.IsSet && notificationId.Value == null)
                throw new ArgumentNullException(nameof(notificationId), "Property is not nullable for class RefundWebhookNotification.");

            if (notificationType.IsSet && notificationType.Value == null)
                throw new ArgumentNullException(nameof(notificationType), "Property is not nullable for class RefundWebhookNotification.");

            if (notificationDate.IsSet && notificationDate.Value == null)
                throw new ArgumentNullException(nameof(notificationDate), "Property is not nullable for class RefundWebhookNotification.");

            if (paymentId.IsSet && paymentId.Value == null)
                throw new ArgumentNullException(nameof(paymentId), "Property is not nullable for class RefundWebhookNotification.");

            if (refund.IsSet && refund.Value == null)
                throw new ArgumentNullException(nameof(refund), "Property is not nullable for class RefundWebhookNotification.");

            return new RefundWebhookNotification(notificationId.Value!.Value!, notificationType.Value!.Value!, notificationDate.Value!.Value!, paymentId.Value!.Value!, refund.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RefundWebhookNotification" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundWebhookNotification"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RefundWebhookNotification refundWebhookNotification, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, refundWebhookNotification, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RefundWebhookNotification" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundWebhookNotification"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RefundWebhookNotification refundWebhookNotification, JsonSerializerOptions jsonSerializerOptions)
        {
            if (refundWebhookNotification.Refund == null)
                throw new ArgumentNullException(nameof(refundWebhookNotification.Refund), "Property is required for class RefundWebhookNotification.");

            writer.WriteString("notificationId", refundWebhookNotification.NotificationId);

            var notificationTypeRawValue = RefundWebhookNotification.NotificationTypeEnumToJsonValue(refundWebhookNotification.NotificationType);
            writer.WriteString("notificationType", notificationTypeRawValue);
            writer.WriteString("notificationDate", refundWebhookNotification.NotificationDate.ToString(NotificationDateFormat));

            writer.WriteString("paymentId", refundWebhookNotification.PaymentId);

            writer.WritePropertyName("refund");
            JsonSerializer.Serialize(writer, refundWebhookNotification.Refund, jsonSerializerOptions);
        }
    }
}
