// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// Defines RefundReason
    /// </summary>
    public enum RefundReason
    {
        /// <summary>
        /// Enum RequestedByCustomer for value: requested_by_customer
        /// </summary>
        RequestedByCustomer = 1,

        /// <summary>
        /// Enum Duplicate for value: duplicate
        /// </summary>
        Duplicate = 2,

        /// <summary>
        /// Enum SuspectedFraud for value: suspected_fraud
        /// </summary>
        SuspectedFraud = 3,

        /// <summary>
        /// Enum Other for value: other
        /// </summary>
        Other = 4
    }

    /// <summary>
    /// Converts <see cref="RefundReason"/> to and from the JSON value
    /// </summary>
    public static class RefundReasonValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="RefundReason"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RefundReason FromString(string value)
        {
            if (value.Equals("requested_by_customer"))
                return RefundReason.RequestedByCustomer;

            if (value.Equals("duplicate"))
                return RefundReason.Duplicate;

            if (value.Equals("suspected_fraud"))
                return RefundReason.SuspectedFraud;

            if (value.Equals("other"))
                return RefundReason.Other;

            throw new NotImplementedException($"Could not convert value to type RefundReason: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="RefundReason"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RefundReason? FromStringOrDefault(string value)
        {
            if (value.Equals("requested_by_customer"))
                return RefundReason.RequestedByCustomer;

            if (value.Equals("duplicate"))
                return RefundReason.Duplicate;

            if (value.Equals("suspected_fraud"))
                return RefundReason.SuspectedFraud;

            if (value.Equals("other"))
                return RefundReason.Other;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="RefundReason"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(RefundReason value)
        {
            if (value == RefundReason.RequestedByCustomer)
                return "requested_by_customer";

            if (value == RefundReason.Duplicate)
                return "duplicate";

            if (value == RefundReason.SuspectedFraud)
                return "suspected_fraud";

            if (value == RefundReason.Other)
                return "other";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RefundReason"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class RefundReasonJsonConverter : JsonConverter<RefundReason>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override RefundReason Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            RefundReason? result = rawValue == null
                ? null
                : RefundReasonValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the RefundReason to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundReason"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, RefundReason refundReason, JsonSerializerOptions options)
        {
            writer.WriteStringValue(RefundReasonValueConverter.ToJsonValue(refundReason).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RefundReason"/>
    /// </summary>
    public class RefundReasonNullableJsonConverter : JsonConverter<RefundReason?>
    {
        /// <summary>
        /// Returns a RefundReason from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override RefundReason? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            RefundReason? result = rawValue == null
                ? null
                : RefundReasonValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the RefundReason to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundReason"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, RefundReason? refundReason, JsonSerializerOptions options)
        {
            if (refundReason.HasValue)
                writer.WriteStringValue(RefundReasonValueConverter.ToJsonValue(refundReason.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }
}
