// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// Суммы принятых возвратов в минимальных единицах валюты платежа. Возвраты в статусе pending не уменьшают refundableAmount.
    /// </summary>
    public partial class RefundSummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundSummary" /> class.
        /// </summary>
        /// <param name="refundedAmount">refundedAmount</param>
        /// <param name="refundableAmount">refundableAmount</param>
        /// <param name="refundCount">refundCount</param>
        [JsonConstructor]
        public RefundSummary(int refundedAmount, int refundableAmount, int refundCount)
        {
            RefundedAmount = refundedAmount;
            RefundableAmount = refundableAmount;
            RefundCount = refundCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RefundedAmount
        /// </summary>
        [JsonPropertyName("refundedAmount")]
        public int RefundedAmount { get; set; }

        /// <summary>
        /// Gets or Sets RefundableAmount
        /// </summary>
        [JsonPropertyName("refundableAmount")]
        public int RefundableAmount { get; set; }

        /// <summary>
        /// Gets or Sets RefundCount
        /// </summary>
        [JsonPropertyName("refundCount")]
        public int RefundCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RefundSummary {\n");
            sb.Append("  RefundedAmount: ").Append(RefundedAmount).Append("\n");
            sb.Append("  RefundableAmount: ").Append(RefundableAmount).Append("\n");
            sb.Append("  RefundCount: ").Append(RefundCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RefundedAmount (int) minimum
            if (this.RefundedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RefundedAmount, must be a value greater than or equal to 0.", new [] { "RefundedAmount" });
            }

            // RefundableAmount (int) minimum
            if (this.RefundableAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RefundableAmount, must be a value greater than or equal to 0.", new [] { "RefundableAmount" });
            }

            // RefundCount (int) minimum
            if (this.RefundCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RefundCount, must be a value greater than or equal to 0.", new [] { "RefundCount" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RefundSummary" />
    /// </summary>
    public partial class RefundSummaryJsonConverter : JsonConverter<RefundSummary>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="RefundSummaryJsonConverter" /> class.
        /// </summary>
        public RefundSummaryJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="RefundSummary" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RefundSummary Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> refundedAmount = default;
            Option<int?> refundableAmount = default;
            Option<int?> refundCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "refundedAmount":
                            refundedAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "refundableAmount":
                            refundableAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "refundCount":
                            refundCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!refundedAmount.IsSet)
                throw new ArgumentException("Property is required for class RefundSummary.", nameof(refundedAmount));

            if (!refundableAmount.IsSet)
                throw new ArgumentException("Property is required for class RefundSummary.", nameof(refundableAmount));

            if (!refundCount.IsSet)
                throw new ArgumentException("Property is required for class RefundSummary.", nameof(refundCount));

            if (refundedAmount.IsSet && refundedAmount.Value == null)
                throw new ArgumentNullException(nameof(refundedAmount), "Property is not nullable for class RefundSummary.");

            if (refundableAmount.IsSet && refundableAmount.Value == null)
                throw new ArgumentNullException(nameof(refundableAmount), "Property is not nullable for class RefundSummary.");

            if (refundCount.IsSet && refundCount.Value == null)
                throw new ArgumentNullException(nameof(refundCount), "Property is not nullable for class RefundSummary.");

            return new RefundSummary(refundedAmount.Value!.Value!, refundableAmount.Value!.Value!, refundCount.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RefundSummary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundSummary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RefundSummary refundSummary, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, refundSummary, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RefundSummary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundSummary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RefundSummary refundSummary, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("refundedAmount", refundSummary.RefundedAmount);

            writer.WriteNumber("refundableAmount", refundSummary.RefundableAmount);

            writer.WriteNumber("refundCount", refundSummary.RefundCount);
        }
    }
}
