// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// RefundPage
    /// </summary>
    public partial class RefundPage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundPage" /> class.
        /// </summary>
        /// <param name="items">items</param>
        /// <param name="nextCursor">Непрозрачный курсор следующей страницы.</param>
        /// <param name="hasMore">hasMore</param>
        [JsonConstructor]
        public RefundPage(List<Refund> items, string nextCursor, bool hasMore)
        {
            Items = items;
            NextCursor = nextCursor;
            HasMore = hasMore;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonPropertyName("items")]
        public List<Refund> Items { get; set; }

        /// <summary>
        /// Непрозрачный курсор следующей страницы.
        /// </summary>
        /// <value>Непрозрачный курсор следующей страницы.</value>
        [JsonPropertyName("nextCursor")]
        public string NextCursor { get; set; }

        /// <summary>
        /// Gets or Sets HasMore
        /// </summary>
        [JsonPropertyName("hasMore")]
        public bool HasMore { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RefundPage {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("  HasMore: ").Append(HasMore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RefundPage" />
    /// </summary>
    public partial class RefundPageJsonConverter : JsonConverter<RefundPage>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="RefundPageJsonConverter" /> class.
        /// </summary>
        public RefundPageJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="RefundPage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RefundPage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Refund>?> items = default;
            Option<string?> nextCursor = default;
            Option<bool?> hasMore = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "items":
                            items = new Option<List<Refund>?>(JsonSerializer.Deserialize<List<Refund>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "nextCursor":
                            nextCursor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hasMore":
                            hasMore = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!items.IsSet)
                throw new ArgumentException("Property is required for class RefundPage.", nameof(items));

            if (!nextCursor.IsSet)
                throw new ArgumentException("Property is required for class RefundPage.", nameof(nextCursor));

            if (!hasMore.IsSet)
                throw new ArgumentException("Property is required for class RefundPage.", nameof(hasMore));

            if (items.IsSet && items.Value == null)
                throw new ArgumentNullException(nameof(items), "Property is not nullable for class RefundPage.");

            if (nextCursor.IsSet && nextCursor.Value == null)
                throw new ArgumentNullException(nameof(nextCursor), "Property is not nullable for class RefundPage.");

            if (hasMore.IsSet && hasMore.Value == null)
                throw new ArgumentNullException(nameof(hasMore), "Property is not nullable for class RefundPage.");

            return new RefundPage(items.Value!, nextCursor.Value!, hasMore.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RefundPage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundPage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RefundPage refundPage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, refundPage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RefundPage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundPage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RefundPage refundPage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (refundPage.Items == null)
                throw new ArgumentNullException(nameof(refundPage.Items), "Property is required for class RefundPage.");

            if (refundPage.NextCursor == null)
                throw new ArgumentNullException(nameof(refundPage.NextCursor), "Property is required for class RefundPage.");

            writer.WritePropertyName("items");
            JsonSerializer.Serialize(writer, refundPage.Items, jsonSerializerOptions);
            writer.WriteString("nextCursor", refundPage.NextCursor);

            writer.WriteBoolean("hasMore", refundPage.HasMore);
        }
    }
}
