// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OPayments.SDK.Client;

namespace OPayments.SDK.Model
{
    /// <summary>
    /// TpayDeviceData
    /// </summary>
    public partial class TpayDeviceData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpayDeviceData" /> class.
        /// </summary>
        /// <param name="platformType">platformType</param>
        /// <param name="os">os</param>
        /// <param name="browser">browser</param>
        /// <param name="language">language</param>
        /// <param name="timezoneName">timezoneName</param>
        /// <param name="userAgent">userAgent</param>
        [JsonConstructor]
        public TpayDeviceData(PlatformTypeEnum platformType, string os, string browser, Option<string?> language = default, Option<string?> timezoneName = default, Option<string?> userAgent = default)
        {
            PlatformType = platformType;
            Os = os;
            Browser = browser;
            LanguageOption = language;
            TimezoneNameOption = timezoneName;
            UserAgentOption = userAgent;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines PlatformType
        /// </summary>
        public enum PlatformTypeEnum
        {
            /// <summary>
            /// Enum Mobile for value: mobile
            /// </summary>
            Mobile = 1,

            /// <summary>
            /// Enum Desktop for value: desktop
            /// </summary>
            Desktop = 2
        }

        /// <summary>
        /// Returns a <see cref="PlatformTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static PlatformTypeEnum PlatformTypeEnumFromString(string value)
        {
            if (value.Equals("mobile"))
                return PlatformTypeEnum.Mobile;

            if (value.Equals("desktop"))
                return PlatformTypeEnum.Desktop;

            throw new NotImplementedException($"Could not convert value to type PlatformTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="PlatformTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PlatformTypeEnum? PlatformTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("mobile"))
                return PlatformTypeEnum.Mobile;

            if (value.Equals("desktop"))
                return PlatformTypeEnum.Desktop;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="PlatformTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string PlatformTypeEnumToJsonValue(PlatformTypeEnum value)
        {
            if (value == PlatformTypeEnum.Mobile)
                return "mobile";

            if (value == PlatformTypeEnum.Desktop)
                return "desktop";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets PlatformType
        /// </summary>
        [JsonPropertyName("platformType")]
        public PlatformTypeEnum PlatformType { get; set; }

        /// <summary>
        /// Gets or Sets Os
        /// </summary>
        [JsonPropertyName("os")]
        public string Os { get; set; }

        /// <summary>
        /// Gets or Sets Browser
        /// </summary>
        [JsonPropertyName("browser")]
        public string Browser { get; set; }

        /// <summary>
        /// Used to track the state of Language
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LanguageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [JsonPropertyName("language")]
        public string? Language { get { return this.LanguageOption.Value; } set { this.LanguageOption = new(value); } }

        /// <summary>
        /// Used to track the state of TimezoneName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TimezoneNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets TimezoneName
        /// </summary>
        [JsonPropertyName("timezoneName")]
        public string? TimezoneName { get { return this.TimezoneNameOption.Value; } set { this.TimezoneNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserAgent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserAgentOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserAgent
        /// </summary>
        [JsonPropertyName("userAgent")]
        public string? UserAgent { get { return this.UserAgentOption.Value; } set { this.UserAgentOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TpayDeviceData {\n");
            sb.Append("  PlatformType: ").Append(PlatformType).Append("\n");
            sb.Append("  Os: ").Append(Os).Append("\n");
            sb.Append("  Browser: ").Append(Browser).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  TimezoneName: ").Append(TimezoneName).Append("\n");
            sb.Append("  UserAgent: ").Append(UserAgent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Os (string) maxLength
            if (this.Os != null && this.Os.Length > 64)
            {
                yield return new ValidationResult("Invalid value for Os, length must be less than 64.", new [] { "Os" });
            }

            // Os (string) minLength
            if (this.Os != null && this.Os.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Os, length must be greater than 1.", new [] { "Os" });
            }

            // Browser (string) maxLength
            if (this.Browser != null && this.Browser.Length > 64)
            {
                yield return new ValidationResult("Invalid value for Browser, length must be less than 64.", new [] { "Browser" });
            }

            // Browser (string) minLength
            if (this.Browser != null && this.Browser.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Browser, length must be greater than 1.", new [] { "Browser" });
            }

            // Language (string) maxLength
            if (this.Language != null && this.Language.Length > 64)
            {
                yield return new ValidationResult("Invalid value for Language, length must be less than 64.", new [] { "Language" });
            }

            // TimezoneName (string) maxLength
            if (this.TimezoneName != null && this.TimezoneName.Length > 128)
            {
                yield return new ValidationResult("Invalid value for TimezoneName, length must be less than 128.", new [] { "TimezoneName" });
            }

            // UserAgent (string) maxLength
            if (this.UserAgent != null && this.UserAgent.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for UserAgent, length must be less than 1024.", new [] { "UserAgent" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TpayDeviceData" />
    /// </summary>
    public partial class TpayDeviceDataJsonConverter : JsonConverter<TpayDeviceData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="TpayDeviceDataJsonConverter" /> class.
        /// </summary>
        public TpayDeviceDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="TpayDeviceData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TpayDeviceData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<TpayDeviceData.PlatformTypeEnum?> platformType = default;
            Option<string?> os = default;
            Option<string?> browser = default;
            Option<string?> language = default;
            Option<string?> timezoneName = default;
            Option<string?> userAgent = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "platformType":
                            string? platformTypeRawValue = utf8JsonReader.GetString();
                            if (platformTypeRawValue != null)
                            {
                                TpayDeviceData.PlatformTypeEnum? platformTypeValue = TpayDeviceData.PlatformTypeEnumFromStringOrDefault(platformTypeRawValue);
                                if (platformTypeValue == null)
                                    throw new JsonException();
                                platformType = new Option<TpayDeviceData.PlatformTypeEnum?>(platformTypeValue);
                            }
                            break;
                        case "os":
                            os = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "browser":
                            browser = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "language":
                            language = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "timezoneName":
                            timezoneName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "userAgent":
                            userAgent = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!platformType.IsSet)
                throw new ArgumentException("Property is required for class TpayDeviceData.", nameof(platformType));

            if (!os.IsSet)
                throw new ArgumentException("Property is required for class TpayDeviceData.", nameof(os));

            if (!browser.IsSet)
                throw new ArgumentException("Property is required for class TpayDeviceData.", nameof(browser));

            if (platformType.IsSet && platformType.Value == null)
                throw new ArgumentNullException(nameof(platformType), "Property is not nullable for class TpayDeviceData.");

            if (os.IsSet && os.Value == null)
                throw new ArgumentNullException(nameof(os), "Property is not nullable for class TpayDeviceData.");

            if (browser.IsSet && browser.Value == null)
                throw new ArgumentNullException(nameof(browser), "Property is not nullable for class TpayDeviceData.");

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class TpayDeviceData.");

            if (timezoneName.IsSet && timezoneName.Value == null)
                throw new ArgumentNullException(nameof(timezoneName), "Property is not nullable for class TpayDeviceData.");

            if (userAgent.IsSet && userAgent.Value == null)
                throw new ArgumentNullException(nameof(userAgent), "Property is not nullable for class TpayDeviceData.");

            return new TpayDeviceData(platformType.Value!.Value!, os.Value!, browser.Value!, language, timezoneName, userAgent);
        }

        /// <summary>
        /// Serializes a <see cref="TpayDeviceData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tpayDeviceData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TpayDeviceData tpayDeviceData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tpayDeviceData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TpayDeviceData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tpayDeviceData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TpayDeviceData tpayDeviceData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tpayDeviceData.Os == null)
                throw new ArgumentNullException(nameof(tpayDeviceData.Os), "Property is required for class TpayDeviceData.");

            if (tpayDeviceData.Browser == null)
                throw new ArgumentNullException(nameof(tpayDeviceData.Browser), "Property is required for class TpayDeviceData.");

            if (tpayDeviceData.LanguageOption.IsSet && tpayDeviceData.Language == null)
                throw new ArgumentNullException(nameof(tpayDeviceData.Language), "Property is required for class TpayDeviceData.");

            if (tpayDeviceData.TimezoneNameOption.IsSet && tpayDeviceData.TimezoneName == null)
                throw new ArgumentNullException(nameof(tpayDeviceData.TimezoneName), "Property is required for class TpayDeviceData.");

            if (tpayDeviceData.UserAgentOption.IsSet && tpayDeviceData.UserAgent == null)
                throw new ArgumentNullException(nameof(tpayDeviceData.UserAgent), "Property is required for class TpayDeviceData.");

            var platformTypeRawValue = TpayDeviceData.PlatformTypeEnumToJsonValue(tpayDeviceData.PlatformType);
            writer.WriteString("platformType", platformTypeRawValue);
            writer.WriteString("os", tpayDeviceData.Os);

            writer.WriteString("browser", tpayDeviceData.Browser);

            if (tpayDeviceData.LanguageOption.IsSet)
                writer.WriteString("language", tpayDeviceData.Language);

            if (tpayDeviceData.TimezoneNameOption.IsSet)
                writer.WriteString("timezoneName", tpayDeviceData.TimezoneName);

            if (tpayDeviceData.UserAgentOption.IsSet)
                writer.WriteString("userAgent", tpayDeviceData.UserAgent);
        }
    }
}
