// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using OPayments.SDK.Client;
using OPayments.SDK.Logging;
using OPayments.SDK.Model;
using System.Diagnostics.CodeAnalysis;

namespace OPayments.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IPaymentApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        PaymentApiEvents Events { get; }

        /// <summary>
        /// Создать платёж по СБП
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="createSbpPaymentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateSbpPaymentApiResponse"/>&gt;</returns>
        Task<ICreateSbpPaymentApiResponse> CreateSbpPaymentAsync(CreateSbpPaymentRequest createSbpPaymentRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Создать платёж по СБП
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="createSbpPaymentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateSbpPaymentApiResponse"/>?&gt;</returns>
        Task<ICreateSbpPaymentApiResponse?> CreateSbpPaymentOrDefaultAsync(CreateSbpPaymentRequest createSbpPaymentRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Создать платёж через T-Pay
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTpayPaymentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateTpayPaymentApiResponse"/>&gt;</returns>
        Task<ICreateTpayPaymentApiResponse> CreateTpayPaymentAsync(CreateTpayPaymentRequest createTpayPaymentRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Создать платёж через T-Pay
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="createTpayPaymentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateTpayPaymentApiResponse"/>?&gt;</returns>
        Task<ICreateTpayPaymentApiResponse?> CreateTpayPaymentOrDefaultAsync(CreateTpayPaymentRequest createTpayPaymentRequest, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ICreateSbpPaymentApiResponse"/>
    /// </summary>
    public interface ICreateSbpPaymentApiResponse : OPayments.SDK.Client.IApiResponse, IOk<OPayments.SDK.Model.Payment?>, ICreated<OPayments.SDK.Model.CreatedPayment?>, IBadRequest<OPayments.SDK.Model.Error?>, IUnauthorized<OPayments.SDK.Model.Error?>, IForbidden<OPayments.SDK.Model.Error?>, IConflict<OPayments.SDK.Model.Error?>, IUnsupportedMediaType<OPayments.SDK.Model.Error?>, ITooManyRequests<OPayments.SDK.Model.Error?>, IBadGateway<OPayments.SDK.Model.Error?>, IServiceUnavailable<OPayments.SDK.Model.Error?>, IGatewayTimeout<OPayments.SDK.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }

        /// <summary>
        /// Returns true if the response is 409 Conflict
        /// </summary>
        /// <returns></returns>
        bool IsConflict { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 502 BadGateway
        /// </summary>
        /// <returns></returns>
        bool IsBadGateway { get; }

        /// <summary>
        /// Returns true if the response is 503 ServiceUnavailable
        /// </summary>
        /// <returns></returns>
        bool IsServiceUnavailable { get; }

        /// <summary>
        /// Returns true if the response is 504 GatewayTimeout
        /// </summary>
        /// <returns></returns>
        bool IsGatewayTimeout { get; }
    }

    /// <summary>
    /// The <see cref="ICreateTpayPaymentApiResponse"/>
    /// </summary>
    public interface ICreateTpayPaymentApiResponse : OPayments.SDK.Client.IApiResponse, IOk<OPayments.SDK.Model.Payment?>, ICreated<OPayments.SDK.Model.CreatedPayment?>, IBadRequest<OPayments.SDK.Model.Error?>, IUnauthorized<OPayments.SDK.Model.Error?>, IForbidden<OPayments.SDK.Model.Error?>, IConflict<OPayments.SDK.Model.Error?>, IUnsupportedMediaType<OPayments.SDK.Model.Error?>, ITooManyRequests<OPayments.SDK.Model.Error?>, IBadGateway<OPayments.SDK.Model.Error?>, IServiceUnavailable<OPayments.SDK.Model.Error?>, IGatewayTimeout<OPayments.SDK.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }

        /// <summary>
        /// Returns true if the response is 409 Conflict
        /// </summary>
        /// <returns></returns>
        bool IsConflict { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 502 BadGateway
        /// </summary>
        /// <returns></returns>
        bool IsBadGateway { get; }

        /// <summary>
        /// Returns true if the response is 503 ServiceUnavailable
        /// </summary>
        /// <returns></returns>
        bool IsServiceUnavailable { get; }

        /// <summary>
        /// Returns true if the response is 504 GatewayTimeout
        /// </summary>
        /// <returns></returns>
        bool IsGatewayTimeout { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class PaymentApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnCreateSbpPayment;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorCreateSbpPayment;

        internal void ExecuteOnCreateSbpPayment(PaymentApi.CreateSbpPaymentApiResponse apiResponse)
        {
            OnCreateSbpPayment?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorCreateSbpPayment(Exception exception)
        {
            OnErrorCreateSbpPayment?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnCreateTpayPayment;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorCreateTpayPayment;

        internal void ExecuteOnCreateTpayPayment(PaymentApi.CreateTpayPaymentApiResponse apiResponse)
        {
            OnCreateTpayPayment?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorCreateTpayPayment(Exception exception)
        {
            OnErrorCreateTpayPayment?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class PaymentApi : IPaymentApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<PaymentApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public PaymentApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PaymentApi(ILogger<PaymentApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, PaymentApiEvents paymentApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = paymentApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatCreateSbpPayment(CreateSbpPaymentRequest createSbpPaymentRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="createSbpPaymentRequest"></param>
        /// <returns></returns>
        private void ValidateCreateSbpPayment(CreateSbpPaymentRequest createSbpPaymentRequest)
        {
            if (createSbpPaymentRequest == null)
                throw new ArgumentNullException(nameof(createSbpPaymentRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="createSbpPaymentRequest"></param>
        private void AfterCreateSbpPaymentDefaultImplementation(ICreateSbpPaymentApiResponse apiResponseLocalVar, CreateSbpPaymentRequest createSbpPaymentRequest)
        {
            bool suppressDefaultLog = false;
            AfterCreateSbpPayment(ref suppressDefaultLog, apiResponseLocalVar, createSbpPaymentRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="createSbpPaymentRequest"></param>
        partial void AfterCreateSbpPayment(ref bool suppressDefaultLog, ICreateSbpPaymentApiResponse apiResponseLocalVar, CreateSbpPaymentRequest createSbpPaymentRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="createSbpPaymentRequest"></param>
        private void OnErrorCreateSbpPaymentDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, CreateSbpPaymentRequest createSbpPaymentRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorCreateSbpPayment(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, createSbpPaymentRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="createSbpPaymentRequest"></param>
        partial void OnErrorCreateSbpPayment(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, CreateSbpPaymentRequest createSbpPaymentRequest);

        /// <summary>
        /// Создать платёж по СБП 
        /// </summary>
        /// <param name="createSbpPaymentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateSbpPaymentApiResponse"/>&gt;</returns>
        public async Task<ICreateSbpPaymentApiResponse?> CreateSbpPaymentOrDefaultAsync(CreateSbpPaymentRequest createSbpPaymentRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await CreateSbpPaymentAsync(createSbpPaymentRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Создать платёж по СБП 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="createSbpPaymentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateSbpPaymentApiResponse"/>&gt;</returns>
        public async Task<ICreateSbpPaymentApiResponse> CreateSbpPaymentAsync(CreateSbpPaymentRequest createSbpPaymentRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateCreateSbpPayment(createSbpPaymentRequest);

                FormatCreateSbpPayment(createSbpPaymentRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/payments/sbp"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/payments/sbp");

                    httpRequestMessageLocalVar.Content = (createSbpPaymentRequest as object) is OPayments.SDK.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(createSbpPaymentRequest, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Signature", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Identity", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        CreateSbpPaymentApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/payments/sbp", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterCreateSbpPaymentDefaultImplementation(apiResponseLocalVar, createSbpPaymentRequest);

                        Events.ExecuteOnCreateSbpPayment(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorCreateSbpPaymentDefaultImplementation(e, "/payments/sbp", uriBuilderLocalVar.Path, createSbpPaymentRequest);
                Events.ExecuteOnErrorCreateSbpPayment(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="CreateSbpPaymentApiResponse"/>
        /// </summary>
        public partial class CreateSbpPaymentApiResponse : OPayments.SDK.Client.ApiResponse, ICreateSbpPaymentApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<PaymentApi> Logger { get; }

            /// <summary>
            /// The <see cref="CreateSbpPaymentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateSbpPaymentApiResponse(ILogger<PaymentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="CreateSbpPaymentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateSbpPaymentApiResponse(ILogger<PaymentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Payment? Ok()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Payment? result = null;
                OnOk(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultOk();
                return result;
            }

            private OPayments.SDK.Model.Payment? DefaultOk()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Payment>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnOk(ref bool suppressDefault, ref OPayments.SDK.Model.Payment? result);

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out OPayments.SDK.Model.Payment? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => 201 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.CreatedPayment? Created()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.CreatedPayment? result = null;
                OnCreated(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultCreated();
                return result;
            }

            private OPayments.SDK.Model.CreatedPayment? DefaultCreated()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsCreated
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.CreatedPayment>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnCreated(ref bool suppressDefault, ref OPayments.SDK.Model.CreatedPayment? result);

            /// <summary>
            /// Returns true if the response is 201 Created and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryCreated([NotNullWhen(true)]out OPayments.SDK.Model.CreatedPayment? result)
            {
                result = null;

                try
                {
                    result = Created();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)201);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? BadRequest()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnBadRequest(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultBadRequest();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultBadRequest()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnBadRequest(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Unauthorized()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnUnauthorized(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnauthorized();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultUnauthorized()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnauthorized(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Forbidden()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnForbidden(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultForbidden();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultForbidden()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnForbidden(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public bool IsConflict => 409 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Conflict()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnConflict(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultConflict();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultConflict()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsConflict
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnConflict(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 409 Conflict and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryConflict([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Conflict();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)409);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? UnsupportedMediaType()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnUnsupportedMediaType(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnsupportedMediaType();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultUnsupportedMediaType()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnsupportedMediaType(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? TooManyRequests()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnTooManyRequests(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultTooManyRequests();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultTooManyRequests()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnTooManyRequests(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 502 BadGateway
            /// </summary>
            /// <returns></returns>
            public bool IsBadGateway => 502 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 502 BadGateway
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? BadGateway()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnBadGateway(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultBadGateway();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultBadGateway()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsBadGateway
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnBadGateway(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 502 BadGateway and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadGateway([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadGateway();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)502);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public bool IsServiceUnavailable => 503 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? ServiceUnavailable()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnServiceUnavailable(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultServiceUnavailable();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultServiceUnavailable()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsServiceUnavailable
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnServiceUnavailable(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryServiceUnavailable([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = ServiceUnavailable();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)503);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 504 GatewayTimeout
            /// </summary>
            /// <returns></returns>
            public bool IsGatewayTimeout => 504 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 504 GatewayTimeout
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? GatewayTimeout()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnGatewayTimeout(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultGatewayTimeout();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultGatewayTimeout()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsGatewayTimeout
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnGatewayTimeout(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 504 GatewayTimeout and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryGatewayTimeout([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = GatewayTimeout();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)504);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatCreateTpayPayment(CreateTpayPaymentRequest createTpayPaymentRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="createTpayPaymentRequest"></param>
        /// <returns></returns>
        private void ValidateCreateTpayPayment(CreateTpayPaymentRequest createTpayPaymentRequest)
        {
            if (createTpayPaymentRequest == null)
                throw new ArgumentNullException(nameof(createTpayPaymentRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="createTpayPaymentRequest"></param>
        private void AfterCreateTpayPaymentDefaultImplementation(ICreateTpayPaymentApiResponse apiResponseLocalVar, CreateTpayPaymentRequest createTpayPaymentRequest)
        {
            bool suppressDefaultLog = false;
            AfterCreateTpayPayment(ref suppressDefaultLog, apiResponseLocalVar, createTpayPaymentRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="createTpayPaymentRequest"></param>
        partial void AfterCreateTpayPayment(ref bool suppressDefaultLog, ICreateTpayPaymentApiResponse apiResponseLocalVar, CreateTpayPaymentRequest createTpayPaymentRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="createTpayPaymentRequest"></param>
        private void OnErrorCreateTpayPaymentDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, CreateTpayPaymentRequest createTpayPaymentRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorCreateTpayPayment(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, createTpayPaymentRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="createTpayPaymentRequest"></param>
        partial void OnErrorCreateTpayPayment(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, CreateTpayPaymentRequest createTpayPaymentRequest);

        /// <summary>
        /// Создать платёж через T-Pay 
        /// </summary>
        /// <param name="createTpayPaymentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateTpayPaymentApiResponse"/>&gt;</returns>
        public async Task<ICreateTpayPaymentApiResponse?> CreateTpayPaymentOrDefaultAsync(CreateTpayPaymentRequest createTpayPaymentRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await CreateTpayPaymentAsync(createTpayPaymentRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Создать платёж через T-Pay 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTpayPaymentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateTpayPaymentApiResponse"/>&gt;</returns>
        public async Task<ICreateTpayPaymentApiResponse> CreateTpayPaymentAsync(CreateTpayPaymentRequest createTpayPaymentRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateCreateTpayPayment(createTpayPaymentRequest);

                FormatCreateTpayPayment(createTpayPaymentRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/payments/tpay"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/payments/tpay");

                    httpRequestMessageLocalVar.Content = (createTpayPaymentRequest as object) is OPayments.SDK.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(createTpayPaymentRequest, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Signature", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Identity", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        CreateTpayPaymentApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/payments/tpay", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterCreateTpayPaymentDefaultImplementation(apiResponseLocalVar, createTpayPaymentRequest);

                        Events.ExecuteOnCreateTpayPayment(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorCreateTpayPaymentDefaultImplementation(e, "/payments/tpay", uriBuilderLocalVar.Path, createTpayPaymentRequest);
                Events.ExecuteOnErrorCreateTpayPayment(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="CreateTpayPaymentApiResponse"/>
        /// </summary>
        public partial class CreateTpayPaymentApiResponse : OPayments.SDK.Client.ApiResponse, ICreateTpayPaymentApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<PaymentApi> Logger { get; }

            /// <summary>
            /// The <see cref="CreateTpayPaymentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateTpayPaymentApiResponse(ILogger<PaymentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="CreateTpayPaymentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateTpayPaymentApiResponse(ILogger<PaymentApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Payment? Ok()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Payment? result = null;
                OnOk(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultOk();
                return result;
            }

            private OPayments.SDK.Model.Payment? DefaultOk()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Payment>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnOk(ref bool suppressDefault, ref OPayments.SDK.Model.Payment? result);

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out OPayments.SDK.Model.Payment? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => 201 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.CreatedPayment? Created()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.CreatedPayment? result = null;
                OnCreated(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultCreated();
                return result;
            }

            private OPayments.SDK.Model.CreatedPayment? DefaultCreated()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsCreated
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.CreatedPayment>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnCreated(ref bool suppressDefault, ref OPayments.SDK.Model.CreatedPayment? result);

            /// <summary>
            /// Returns true if the response is 201 Created and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryCreated([NotNullWhen(true)]out OPayments.SDK.Model.CreatedPayment? result)
            {
                result = null;

                try
                {
                    result = Created();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)201);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? BadRequest()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnBadRequest(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultBadRequest();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultBadRequest()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnBadRequest(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Unauthorized()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnUnauthorized(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnauthorized();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultUnauthorized()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnauthorized(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Forbidden()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnForbidden(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultForbidden();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultForbidden()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnForbidden(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public bool IsConflict => 409 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Conflict()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnConflict(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultConflict();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultConflict()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsConflict
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnConflict(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 409 Conflict and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryConflict([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Conflict();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)409);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? UnsupportedMediaType()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnUnsupportedMediaType(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnsupportedMediaType();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultUnsupportedMediaType()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnsupportedMediaType(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? TooManyRequests()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnTooManyRequests(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultTooManyRequests();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultTooManyRequests()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnTooManyRequests(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 502 BadGateway
            /// </summary>
            /// <returns></returns>
            public bool IsBadGateway => 502 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 502 BadGateway
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? BadGateway()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnBadGateway(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultBadGateway();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultBadGateway()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsBadGateway
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnBadGateway(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 502 BadGateway and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadGateway([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadGateway();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)502);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public bool IsServiceUnavailable => 503 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? ServiceUnavailable()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnServiceUnavailable(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultServiceUnavailable();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultServiceUnavailable()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsServiceUnavailable
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnServiceUnavailable(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryServiceUnavailable([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = ServiceUnavailable();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)503);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 504 GatewayTimeout
            /// </summary>
            /// <returns></returns>
            public bool IsGatewayTimeout => 504 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 504 GatewayTimeout
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? GatewayTimeout()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnGatewayTimeout(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultGatewayTimeout();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultGatewayTimeout()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsGatewayTimeout
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnGatewayTimeout(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 504 GatewayTimeout and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryGatewayTimeout([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = GatewayTimeout();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)504);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
