// <auto-generated>
/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using OPayments.SDK.Client;
using OPayments.SDK.Logging;
using OPayments.SDK.Model;
using System.Diagnostics.CodeAnalysis;

namespace OPayments.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IRefundsApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        RefundsApiEvents Events { get; }

        /// <summary>
        /// Создать возврат
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentId"></param>
        /// <param name="createRefundRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreatePaymentRefundApiResponse"/>&gt;</returns>
        Task<ICreatePaymentRefundApiResponse> CreatePaymentRefundAsync(Guid paymentId, CreateRefundRequest createRefundRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Создать возврат
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="paymentId"></param>
        /// <param name="createRefundRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreatePaymentRefundApiResponse"/>?&gt;</returns>
        Task<ICreatePaymentRefundApiResponse?> CreatePaymentRefundOrDefaultAsync(Guid paymentId, CreateRefundRequest createRefundRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Получить возврат
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetPaymentRefundApiResponse"/>&gt;</returns>
        Task<IGetPaymentRefundApiResponse> GetPaymentRefundAsync(Guid paymentId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Получить возврат
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="paymentId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetPaymentRefundApiResponse"/>?&gt;</returns>
        Task<IGetPaymentRefundApiResponse?> GetPaymentRefundOrDefaultAsync(Guid paymentId, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ICreatePaymentRefundApiResponse"/>
    /// </summary>
    public interface ICreatePaymentRefundApiResponse : OPayments.SDK.Client.IApiResponse, IOk<OPayments.SDK.Model.Refund?>, IAccepted<OPayments.SDK.Model.PendingRefund?>, IBadRequest<OPayments.SDK.Model.Error?>, IUnauthorized<OPayments.SDK.Model.Error?>, INotFound<OPayments.SDK.Model.Error?>, IConflict<OPayments.SDK.Model.Error?>, IUnsupportedMediaType<OPayments.SDK.Model.Error?>, IUnprocessableContent<OPayments.SDK.Model.Error?>, ITooManyRequests<OPayments.SDK.Model.Error?>, IInternalServerError<OPayments.SDK.Model.Error?>, IBadGateway<OPayments.SDK.Model.Error?>, IServiceUnavailable<OPayments.SDK.Model.Error?>, IGatewayTimeout<OPayments.SDK.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 202 Accepted
        /// </summary>
        /// <returns></returns>
        bool IsAccepted { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 409 Conflict
        /// </summary>
        /// <returns></returns>
        bool IsConflict { get; }

        /// <summary>
        /// Returns true if the response is 415 UnsupportedMediaType
        /// </summary>
        /// <returns></returns>
        bool IsUnsupportedMediaType { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is 502 BadGateway
        /// </summary>
        /// <returns></returns>
        bool IsBadGateway { get; }

        /// <summary>
        /// Returns true if the response is 503 ServiceUnavailable
        /// </summary>
        /// <returns></returns>
        bool IsServiceUnavailable { get; }

        /// <summary>
        /// Returns true if the response is 504 GatewayTimeout
        /// </summary>
        /// <returns></returns>
        bool IsGatewayTimeout { get; }
    }

    /// <summary>
    /// The <see cref="IGetPaymentRefundApiResponse"/>
    /// </summary>
    public interface IGetPaymentRefundApiResponse : OPayments.SDK.Client.IApiResponse, IOk<OPayments.SDK.Model.Refund?>, IBadRequest<OPayments.SDK.Model.Error?>, IUnauthorized<OPayments.SDK.Model.Error?>, INotFound<OPayments.SDK.Model.Error?>, ITooManyRequests<OPayments.SDK.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class RefundsApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnCreatePaymentRefund;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorCreatePaymentRefund;

        internal void ExecuteOnCreatePaymentRefund(RefundsApi.CreatePaymentRefundApiResponse apiResponse)
        {
            OnCreatePaymentRefund?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorCreatePaymentRefund(Exception exception)
        {
            OnErrorCreatePaymentRefund?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetPaymentRefund;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetPaymentRefund;

        internal void ExecuteOnGetPaymentRefund(RefundsApi.GetPaymentRefundApiResponse apiResponse)
        {
            OnGetPaymentRefund?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetPaymentRefund(Exception exception)
        {
            OnErrorGetPaymentRefund?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class RefundsApi : IRefundsApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<RefundsApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public RefundsApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="RefundsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RefundsApi(ILogger<RefundsApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, RefundsApiEvents refundsApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = refundsApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatCreatePaymentRefund(ref Guid paymentId, CreateRefundRequest createRefundRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="createRefundRequest"></param>
        /// <returns></returns>
        private void ValidateCreatePaymentRefund(CreateRefundRequest createRefundRequest)
        {
            if (createRefundRequest == null)
                throw new ArgumentNullException(nameof(createRefundRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="paymentId"></param>
        /// <param name="createRefundRequest"></param>
        private void AfterCreatePaymentRefundDefaultImplementation(ICreatePaymentRefundApiResponse apiResponseLocalVar, Guid paymentId, CreateRefundRequest createRefundRequest)
        {
            bool suppressDefaultLog = false;
            AfterCreatePaymentRefund(ref suppressDefaultLog, apiResponseLocalVar, paymentId, createRefundRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="paymentId"></param>
        /// <param name="createRefundRequest"></param>
        partial void AfterCreatePaymentRefund(ref bool suppressDefaultLog, ICreatePaymentRefundApiResponse apiResponseLocalVar, Guid paymentId, CreateRefundRequest createRefundRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="paymentId"></param>
        /// <param name="createRefundRequest"></param>
        private void OnErrorCreatePaymentRefundDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid paymentId, CreateRefundRequest createRefundRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorCreatePaymentRefund(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, paymentId, createRefundRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="paymentId"></param>
        /// <param name="createRefundRequest"></param>
        partial void OnErrorCreatePaymentRefund(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid paymentId, CreateRefundRequest createRefundRequest);

        /// <summary>
        /// Создать возврат 
        /// </summary>
        /// <param name="paymentId"></param>
        /// <param name="createRefundRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreatePaymentRefundApiResponse"/>&gt;</returns>
        public async Task<ICreatePaymentRefundApiResponse?> CreatePaymentRefundOrDefaultAsync(Guid paymentId, CreateRefundRequest createRefundRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await CreatePaymentRefundAsync(paymentId, createRefundRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Создать возврат 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentId"></param>
        /// <param name="createRefundRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreatePaymentRefundApiResponse"/>&gt;</returns>
        public async Task<ICreatePaymentRefundApiResponse> CreatePaymentRefundAsync(Guid paymentId, CreateRefundRequest createRefundRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateCreatePaymentRefund(createRefundRequest);

                FormatCreatePaymentRefund(ref paymentId, createRefundRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/payments/{paymentId}/refund"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/payments/{paymentId}/refund");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BpaymentId%7D", Uri.EscapeDataString(paymentId.ToString()));

                    httpRequestMessageLocalVar.Content = (createRefundRequest as object) is OPayments.SDK.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(createRefundRequest, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Signature", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Identity", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        CreatePaymentRefundApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/payments/{paymentId}/refund", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterCreatePaymentRefundDefaultImplementation(apiResponseLocalVar, paymentId, createRefundRequest);

                        Events.ExecuteOnCreatePaymentRefund(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorCreatePaymentRefundDefaultImplementation(e, "/payments/{paymentId}/refund", uriBuilderLocalVar.Path, paymentId, createRefundRequest);
                Events.ExecuteOnErrorCreatePaymentRefund(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="CreatePaymentRefundApiResponse"/>
        /// </summary>
        public partial class CreatePaymentRefundApiResponse : OPayments.SDK.Client.ApiResponse, ICreatePaymentRefundApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<RefundsApi> Logger { get; }

            /// <summary>
            /// The <see cref="CreatePaymentRefundApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreatePaymentRefundApiResponse(ILogger<RefundsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="CreatePaymentRefundApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreatePaymentRefundApiResponse(ILogger<RefundsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Refund? Ok()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Refund? result = null;
                OnOk(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultOk();
                return result;
            }

            private OPayments.SDK.Model.Refund? DefaultOk()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Refund>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnOk(ref bool suppressDefault, ref OPayments.SDK.Model.Refund? result);

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out OPayments.SDK.Model.Refund? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 202 Accepted
            /// </summary>
            /// <returns></returns>
            public bool IsAccepted => 202 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 202 Accepted
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.PendingRefund? Accepted()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.PendingRefund? result = null;
                OnAccepted(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultAccepted();
                return result;
            }

            private OPayments.SDK.Model.PendingRefund? DefaultAccepted()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsAccepted
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.PendingRefund>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnAccepted(ref bool suppressDefault, ref OPayments.SDK.Model.PendingRefund? result);

            /// <summary>
            /// Returns true if the response is 202 Accepted and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryAccepted([NotNullWhen(true)]out OPayments.SDK.Model.PendingRefund? result)
            {
                result = null;

                try
                {
                    result = Accepted();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)202);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? BadRequest()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnBadRequest(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultBadRequest();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultBadRequest()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnBadRequest(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Unauthorized()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnUnauthorized(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnauthorized();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultUnauthorized()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnauthorized(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? NotFound()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnNotFound(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultNotFound();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultNotFound()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnNotFound(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public bool IsConflict => 409 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Conflict()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnConflict(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultConflict();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultConflict()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsConflict
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnConflict(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 409 Conflict and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryConflict([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Conflict();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)409);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public bool IsUnsupportedMediaType => 415 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 415 UnsupportedMediaType
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? UnsupportedMediaType()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnUnsupportedMediaType(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnsupportedMediaType();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultUnsupportedMediaType()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnsupportedMediaType
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnsupportedMediaType(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 415 UnsupportedMediaType and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnsupportedMediaType([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnsupportedMediaType();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)415);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? UnprocessableContent()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnUnprocessableContent(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnprocessableContent();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultUnprocessableContent()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnprocessableContent(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? TooManyRequests()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnTooManyRequests(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultTooManyRequests();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultTooManyRequests()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnTooManyRequests(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? InternalServerError()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnInternalServerError(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultInternalServerError();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultInternalServerError()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnInternalServerError(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 502 BadGateway
            /// </summary>
            /// <returns></returns>
            public bool IsBadGateway => 502 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 502 BadGateway
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? BadGateway()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnBadGateway(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultBadGateway();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultBadGateway()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsBadGateway
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnBadGateway(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 502 BadGateway and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadGateway([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadGateway();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)502);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public bool IsServiceUnavailable => 503 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? ServiceUnavailable()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnServiceUnavailable(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultServiceUnavailable();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultServiceUnavailable()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsServiceUnavailable
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnServiceUnavailable(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryServiceUnavailable([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = ServiceUnavailable();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)503);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 504 GatewayTimeout
            /// </summary>
            /// <returns></returns>
            public bool IsGatewayTimeout => 504 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 504 GatewayTimeout
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? GatewayTimeout()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnGatewayTimeout(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultGatewayTimeout();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultGatewayTimeout()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsGatewayTimeout
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnGatewayTimeout(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 504 GatewayTimeout and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryGatewayTimeout([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = GatewayTimeout();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)504);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetPaymentRefund(ref Guid paymentId);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="paymentId"></param>
        private void AfterGetPaymentRefundDefaultImplementation(IGetPaymentRefundApiResponse apiResponseLocalVar, Guid paymentId)
        {
            bool suppressDefaultLog = false;
            AfterGetPaymentRefund(ref suppressDefaultLog, apiResponseLocalVar, paymentId);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="paymentId"></param>
        partial void AfterGetPaymentRefund(ref bool suppressDefaultLog, IGetPaymentRefundApiResponse apiResponseLocalVar, Guid paymentId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="paymentId"></param>
        private void OnErrorGetPaymentRefundDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid paymentId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetPaymentRefund(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, paymentId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="paymentId"></param>
        partial void OnErrorGetPaymentRefund(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Guid paymentId);

        /// <summary>
        /// Получить возврат 
        /// </summary>
        /// <param name="paymentId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetPaymentRefundApiResponse"/>&gt;</returns>
        public async Task<IGetPaymentRefundApiResponse?> GetPaymentRefundOrDefaultAsync(Guid paymentId, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetPaymentRefundAsync(paymentId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Получить возврат 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="paymentId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetPaymentRefundApiResponse"/>&gt;</returns>
        public async Task<IGetPaymentRefundApiResponse> GetPaymentRefundAsync(Guid paymentId, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatGetPaymentRefund(ref paymentId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/payments/{paymentId}/refund"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/payments/{paymentId}/refund");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BpaymentId%7D", Uri.EscapeDataString(paymentId.ToString()));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Signature", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Identity", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        GetPaymentRefundApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/payments/{paymentId}/refund", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetPaymentRefundDefaultImplementation(apiResponseLocalVar, paymentId);

                        Events.ExecuteOnGetPaymentRefund(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetPaymentRefundDefaultImplementation(e, "/payments/{paymentId}/refund", uriBuilderLocalVar.Path, paymentId);
                Events.ExecuteOnErrorGetPaymentRefund(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetPaymentRefundApiResponse"/>
        /// </summary>
        public partial class GetPaymentRefundApiResponse : OPayments.SDK.Client.ApiResponse, IGetPaymentRefundApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<RefundsApi> Logger { get; }

            /// <summary>
            /// The <see cref="GetPaymentRefundApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetPaymentRefundApiResponse(ILogger<RefundsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetPaymentRefundApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetPaymentRefundApiResponse(ILogger<RefundsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Refund? Ok()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Refund? result = null;
                OnOk(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultOk();
                return result;
            }

            private OPayments.SDK.Model.Refund? DefaultOk()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Refund>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnOk(ref bool suppressDefault, ref OPayments.SDK.Model.Refund? result);

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out OPayments.SDK.Model.Refund? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? BadRequest()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnBadRequest(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultBadRequest();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultBadRequest()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnBadRequest(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? Unauthorized()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnUnauthorized(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultUnauthorized();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultUnauthorized()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnUnauthorized(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? NotFound()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnNotFound(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultNotFound();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultNotFound()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnNotFound(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public OPayments.SDK.Model.Error? TooManyRequests()
            {
                bool suppressDefault = false;
                OPayments.SDK.Model.Error? result = null;
                OnTooManyRequests(ref suppressDefault, ref result);
                if (!suppressDefault)
                    result = DefaultTooManyRequests();
                return result;
            }

            private OPayments.SDK.Model.Error? DefaultTooManyRequests()
            {
                // NOTICE: Consider this AsModel template deprecated. Implement the appropriate partial method instead
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<OPayments.SDK.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            partial void OnTooManyRequests(ref bool suppressDefault, ref OPayments.SDK.Model.Error? result);

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out OPayments.SDK.Model.Error? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
