/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OPayments.SDK.Model;
using OPayments.SDK.Client;
using System.Reflection;

namespace OPayments.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing Balance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BalanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Balance
        //private Balance instance;

        public BalanceTests()
        {
            // TODO uncomment below to create an instance of Balance
            //instance = new Balance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Balance
        /// </summary>
        [Fact]
        public void BalanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Balance
            //Assert.IsType<Balance>(instance);
        }

        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }

        /// <summary>
        /// Test the property 'VarBalance'
        /// </summary>
        [Fact]
        public void VarBalanceTest()
        {
            // TODO unit test for the property 'VarBalance'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
    }
}
