/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OPayments.SDK.Model;
using OPayments.SDK.Client;
using System.Reflection;

namespace OPayments.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceData
        //private DeviceData instance;

        public DeviceDataTests()
        {
            // TODO uncomment below to create an instance of DeviceData
            //instance = new DeviceData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceData
        /// </summary>
        [Fact]
        public void DeviceDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceData
            //Assert.IsType<DeviceData>(instance);
        }

        /// <summary>
        /// Test the property 'PlatformType'
        /// </summary>
        [Fact]
        public void PlatformTypeTest()
        {
            // TODO unit test for the property 'PlatformType'
        }

        /// <summary>
        /// Test the property 'Os'
        /// </summary>
        [Fact]
        public void OsTest()
        {
            // TODO unit test for the property 'Os'
        }

        /// <summary>
        /// Test the property 'Browser'
        /// </summary>
        [Fact]
        public void BrowserTest()
        {
            // TODO unit test for the property 'Browser'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'TimezoneName'
        /// </summary>
        [Fact]
        public void TimezoneNameTest()
        {
            // TODO unit test for the property 'TimezoneName'
        }

        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
    }
}
