/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OPayments.SDK.Model;
using OPayments.SDK.Client;
using System.Reflection;

namespace OPayments.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorErrorDetailsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorErrorDetailsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorErrorDetailsInner
        //private ErrorErrorDetailsInner instance;

        public ErrorErrorDetailsInnerTests()
        {
            // TODO uncomment below to create an instance of ErrorErrorDetailsInner
            //instance = new ErrorErrorDetailsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorErrorDetailsInner
        /// </summary>
        [Fact]
        public void ErrorErrorDetailsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorErrorDetailsInner
            //Assert.IsType<ErrorErrorDetailsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
