/*
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OPayments.SDK.Model;
using OPayments.SDK.Client;
using System.Reflection;

namespace OPayments.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing PrepaymentWebhookNotification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrepaymentWebhookNotificationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrepaymentWebhookNotification
        //private PrepaymentWebhookNotification instance;

        public PrepaymentWebhookNotificationTests()
        {
            // TODO uncomment below to create an instance of PrepaymentWebhookNotification
            //instance = new PrepaymentWebhookNotification();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrepaymentWebhookNotification
        /// </summary>
        [Fact]
        public void PrepaymentWebhookNotificationInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrepaymentWebhookNotification
            //Assert.IsType<PrepaymentWebhookNotification>(instance);
        }

        /// <summary>
        /// Test the property 'NotificationId'
        /// </summary>
        [Fact]
        public void NotificationIdTest()
        {
            // TODO unit test for the property 'NotificationId'
        }

        /// <summary>
        /// Test the property 'NotificationType'
        /// </summary>
        [Fact]
        public void NotificationTypeTest()
        {
            // TODO unit test for the property 'NotificationType'
        }

        /// <summary>
        /// Test the property 'NotificationDate'
        /// </summary>
        [Fact]
        public void NotificationDateTest()
        {
            // TODO unit test for the property 'NotificationDate'
        }

        /// <summary>
        /// Test the property 'Payment'
        /// </summary>
        [Fact]
        public void PaymentTest()
        {
            // TODO unit test for the property 'Payment'
        }
    }
}
